package com.healthcare.db.client;

import com.healthcare.db.model.Analyzer;
import com.healthcare.db.model.AnalyzerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnalyzerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int countByExample(AnalyzerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int deleteByExample(AnalyzerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int deleteByPrimaryKey(Integer analyzerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int insert(Analyzer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int insertSelective(Analyzer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	List<Analyzer> selectByExample(AnalyzerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	Analyzer selectByPrimaryKey(Integer analyzerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int updateByExampleSelective(@Param("record") Analyzer record,
			@Param("example") AnalyzerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int updateByExample(@Param("record") Analyzer record,
			@Param("example") AnalyzerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int updateByPrimaryKeySelective(Analyzer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	int updateByPrimaryKey(Analyzer record);
}