package com.healthcare.db.client;

import com.healthcare.db.model.Newtestitem;
import com.healthcare.db.model.NewtestitemExample;
import com.healthcare.db.model.NewtestitemWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewtestitemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newtestitem
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int countByExample(NewtestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newtestitem
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int deleteByExample(NewtestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newtestitem
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int insert(Newtestitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newtestitem
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int insertSelective(Newtestitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newtestitem
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	List<Newtestitem> selectByExample(NewtestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newtestitem
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByExampleSelective(@Param("record") Newtestitem record,
			@Param("example") NewtestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table newtestitem
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByExample(@Param("record") Newtestitem record,
			@Param("example") NewtestitemExample example);
}