package com.healthcare.db.client;

import com.healthcare.db.model.Qcitem;
import com.healthcare.db.model.QcitemExample;
import com.healthcare.db.model.QcitemKey;
import com.healthcare.db.model.TestitemExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface QcitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int countByExample(QcitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int deleteByExample(QcitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int deleteByPrimaryKey(QcitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int insert(Qcitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int insertSelective(Qcitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    List<Qcitem> selectByExample(QcitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    Qcitem selectByPrimaryKey(QcitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int updateByExampleSelective(@Param("record") Qcitem record, @Param("example") QcitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int updateByExample(@Param("record") Qcitem record, @Param("example") QcitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int updateByPrimaryKeySelective(Qcitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcitem
     *
     * @mbggenerated Thu Sep 25 08:43:14 ICT 2014
     */
    int updateByPrimaryKey(Qcitem record);
    
    int createTable(QcitemExample example);
    
    List<String> showTable(QcitemExample example );
    
}