package com.healthcare.db.client;

import com.healthcare.db.model.StationStat;
import com.healthcare.db.model.StationStatExample;
import com.healthcare.db.model.StationStatKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StationStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int countByExample(StationStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int deleteByExample(StationStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int deleteByPrimaryKey(StationStatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int insert(StationStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int insertSelective(StationStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    List<StationStat> selectByExample(StationStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    StationStat selectByPrimaryKey(StationStatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int updateByExampleSelective(@Param("record") StationStat record, @Param("example") StationStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int updateByExample(@Param("record") StationStat record, @Param("example") StationStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int updateByPrimaryKeySelective(StationStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_stat
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    int updateByPrimaryKey(StationStat record);
}