package com.healthcare.db.client;

import com.healthcare.db.model.Testitem;
import com.healthcare.db.model.TestitemExample;
import com.healthcare.db.model.TestitemWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestitemMapper {
	
	
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	int countByExample(TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	int deleteByExample(TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	int insert(Testitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	int insertSelective(Testitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	List<Testitem> selectByExampleWithBLOBs(TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	List<Testitem> selectByExample(TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	int updateByExampleSelective(@Param("record") Testitem record,
			@Param("example") TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") Testitem record,
			@Param("example") TestitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table testitem
	 * @mbggenerated  Mon Sep 22 15:06:06 ICT 2014
	 */
	int updateByExample(@Param("record") Testitem record,
			@Param("example") TestitemExample example);

	int createTable(TestitemExample example);
    
    List<String> showTable(TestitemExample example );
}