package com.healthcare.db.client;

import com.healthcare.db.model.WardGroup;
import com.healthcare.db.model.WardGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WardGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int countByExample(WardGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int deleteByExample(WardGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int insert(WardGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int insertSelective(WardGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    List<WardGroup> selectByExample(WardGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    WardGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int updateByExampleSelective(@Param("record") WardGroup record, @Param("example") WardGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int updateByExample(@Param("record") WardGroup record, @Param("example") WardGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int updateByPrimaryKeySelective(WardGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ward_group
     *
     * @mbggenerated Tue Jun 16 02:58:03 ICT 2015
     */
    int updateByPrimaryKey(WardGroup record);
}