package com.healthcare.db.model;

public class ActWithBLOBs extends Act {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act.table_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String table;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act.column_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String column;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act.value_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act.table_
	 * @return  the value of act.table_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getTable() {
		return table;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act.table_
	 * @param table  the value for act.table_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setTable(String table) {
		this.table = table;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act.column_
	 * @return  the value of act.column_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getColumn() {
		return column;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act.column_
	 * @param column  the value for act.column_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setColumn(String column) {
		this.column = column;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act.value_
	 * @return  the value of act.value_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act.value_
	 * @param value  the value for act.value_
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setValue(String value) {
		this.value = value;
	}
}