package com.healthcare.db.model;

public class AnalyzerGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analyzer_group.group_id
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analyzer_group.group_name
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analyzer_group.group_description
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    private String groupDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analyzer_group.group_id
     *
     * @return the value of analyzer_group.group_id
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analyzer_group.group_id
     *
     * @param groupId the value for analyzer_group.group_id
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analyzer_group.group_name
     *
     * @return the value of analyzer_group.group_name
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analyzer_group.group_name
     *
     * @param groupName the value for analyzer_group.group_name
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analyzer_group.group_description
     *
     * @return the value of analyzer_group.group_description
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    public String getGroupDescription() {
        return groupDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analyzer_group.group_description
     *
     * @param groupDescription the value for analyzer_group.group_description
     *
     * @mbggenerated Tue Jun 16 03:39:42 ICT 2015
     */
    public void setGroupDescription(String groupDescription) {
        this.groupDescription = groupDescription;
    }
}