package com.healthcare.db.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IqmDatasetExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public IqmDatasetExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIqmDataSetIdIsNull() {
			addCriterion("iqm_data_set_id is null");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdIsNotNull() {
			addCriterion("iqm_data_set_id is not null");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdEqualTo(Integer value) {
			addCriterion("iqm_data_set_id =", value, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdNotEqualTo(Integer value) {
			addCriterion("iqm_data_set_id <>", value, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdGreaterThan(Integer value) {
			addCriterion("iqm_data_set_id >", value, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("iqm_data_set_id >=", value, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdLessThan(Integer value) {
			addCriterion("iqm_data_set_id <", value, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdLessThanOrEqualTo(Integer value) {
			addCriterion("iqm_data_set_id <=", value, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdIn(List<Integer> values) {
			addCriterion("iqm_data_set_id in", values, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdNotIn(List<Integer> values) {
			addCriterion("iqm_data_set_id not in", values, "iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdBetween(Integer value1, Integer value2) {
			addCriterion("iqm_data_set_id between", value1, value2,
					"iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andIqmDataSetIdNotBetween(Integer value1, Integer value2) {
			addCriterion("iqm_data_set_id not between", value1, value2,
					"iqmDataSetId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNull() {
			addCriterion("analyzer_id is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNotNull() {
			addCriterion("analyzer_id is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdEqualTo(Integer value) {
			addCriterion("analyzer_id =", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotEqualTo(Integer value) {
			addCriterion("analyzer_id <>", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThan(Integer value) {
			addCriterion("analyzer_id >", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id >=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThan(Integer value) {
			addCriterion("analyzer_id <", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id <=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIn(List<Integer> values) {
			addCriterion("analyzer_id in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotIn(List<Integer> values) {
			addCriterion("analyzer_id not in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id between", value1, value2, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id not between", value1, value2,
					"analyzerId");
			return (Criteria) this;
		}

		public Criteria andDataMonthIsNull() {
			addCriterion("data_month is null");
			return (Criteria) this;
		}

		public Criteria andDataMonthIsNotNull() {
			addCriterion("data_month is not null");
			return (Criteria) this;
		}

		public Criteria andDataMonthEqualTo(Date value) {
			addCriterion("data_month =", value, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthNotEqualTo(Date value) {
			addCriterion("data_month <>", value, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthGreaterThan(Date value) {
			addCriterion("data_month >", value, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthGreaterThanOrEqualTo(Date value) {
			addCriterion("data_month >=", value, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthLessThan(Date value) {
			addCriterion("data_month <", value, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthLessThanOrEqualTo(Date value) {
			addCriterion("data_month <=", value, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthIn(List<Date> values) {
			addCriterion("data_month in", values, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthNotIn(List<Date> values) {
			addCriterion("data_month not in", values, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthBetween(Date value1, Date value2) {
			addCriterion("data_month between", value1, value2, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andDataMonthNotBetween(Date value1, Date value2) {
			addCriterion("data_month not between", value1, value2, "dataMonth");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysIsNull() {
			addCriterion("catridge_insertion_days is null");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysIsNotNull() {
			addCriterion("catridge_insertion_days is not null");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysEqualTo(String value) {
			addCriterion("catridge_insertion_days =", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysNotEqualTo(String value) {
			addCriterion("catridge_insertion_days <>", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysGreaterThan(String value) {
			addCriterion("catridge_insertion_days >", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysGreaterThanOrEqualTo(
				String value) {
			addCriterion("catridge_insertion_days >=", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysLessThan(String value) {
			addCriterion("catridge_insertion_days <", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysLessThanOrEqualTo(String value) {
			addCriterion("catridge_insertion_days <=", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysLike(String value) {
			addCriterion("catridge_insertion_days like", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysNotLike(String value) {
			addCriterion("catridge_insertion_days not like", value,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysIn(List<String> values) {
			addCriterion("catridge_insertion_days in", values,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysNotIn(List<String> values) {
			addCriterion("catridge_insertion_days not in", values,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysBetween(String value1,
				String value2) {
			addCriterion("catridge_insertion_days between", value1, value2,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeInsertionDaysNotBetween(String value1,
				String value2) {
			addCriterion("catridge_insertion_days not between", value1, value2,
					"catridgeInsertionDays");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsIsNull() {
			addCriterion("catridge_lots is null");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsIsNotNull() {
			addCriterion("catridge_lots is not null");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsEqualTo(String value) {
			addCriterion("catridge_lots =", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsNotEqualTo(String value) {
			addCriterion("catridge_lots <>", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsGreaterThan(String value) {
			addCriterion("catridge_lots >", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsGreaterThanOrEqualTo(String value) {
			addCriterion("catridge_lots >=", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsLessThan(String value) {
			addCriterion("catridge_lots <", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsLessThanOrEqualTo(String value) {
			addCriterion("catridge_lots <=", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsLike(String value) {
			addCriterion("catridge_lots like", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsNotLike(String value) {
			addCriterion("catridge_lots not like", value, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsIn(List<String> values) {
			addCriterion("catridge_lots in", values, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsNotIn(List<String> values) {
			addCriterion("catridge_lots not in", values, "catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsBetween(String value1, String value2) {
			addCriterion("catridge_lots between", value1, value2,
					"catridgeLots");
			return (Criteria) this;
		}

		public Criteria andCatridgeLotsNotBetween(String value1, String value2) {
			addCriterion("catridge_lots not between", value1, value2,
					"catridgeLots");
			return (Criteria) this;
		}

		public Criteria andDataParameterIsNull() {
			addCriterion("data_parameter is null");
			return (Criteria) this;
		}

		public Criteria andDataParameterIsNotNull() {
			addCriterion("data_parameter is not null");
			return (Criteria) this;
		}

		public Criteria andDataParameterEqualTo(String value) {
			addCriterion("data_parameter =", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterNotEqualTo(String value) {
			addCriterion("data_parameter <>", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterGreaterThan(String value) {
			addCriterion("data_parameter >", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterGreaterThanOrEqualTo(String value) {
			addCriterion("data_parameter >=", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterLessThan(String value) {
			addCriterion("data_parameter <", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterLessThanOrEqualTo(String value) {
			addCriterion("data_parameter <=", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterLike(String value) {
			addCriterion("data_parameter like", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterNotLike(String value) {
			addCriterion("data_parameter not like", value, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterIn(List<String> values) {
			addCriterion("data_parameter in", values, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterNotIn(List<String> values) {
			addCriterion("data_parameter not in", values, "dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterBetween(String value1, String value2) {
			addCriterion("data_parameter between", value1, value2,
					"dataParameter");
			return (Criteria) this;
		}

		public Criteria andDataParameterNotBetween(String value1, String value2) {
			addCriterion("data_parameter not between", value1, value2,
					"dataParameter");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueIsNull() {
			addCriterion("nominal_target_value is null");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueIsNotNull() {
			addCriterion("nominal_target_value is not null");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueEqualTo(Double value) {
			addCriterion("nominal_target_value =", value, "nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueNotEqualTo(Double value) {
			addCriterion("nominal_target_value <>", value, "nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueGreaterThan(Double value) {
			addCriterion("nominal_target_value >", value, "nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueGreaterThanOrEqualTo(Double value) {
			addCriterion("nominal_target_value >=", value, "nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueLessThan(Double value) {
			addCriterion("nominal_target_value <", value, "nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueLessThanOrEqualTo(Double value) {
			addCriterion("nominal_target_value <=", value, "nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueIn(List<Double> values) {
			addCriterion("nominal_target_value in", values,
					"nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueNotIn(List<Double> values) {
			addCriterion("nominal_target_value not in", values,
					"nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueBetween(Double value1,
				Double value2) {
			addCriterion("nominal_target_value between", value1, value2,
					"nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andNominalTargetValueNotBetween(Double value1,
				Double value2) {
			addCriterion("nominal_target_value not between", value1, value2,
					"nominalTargetValue");
			return (Criteria) this;
		}

		public Criteria andDataMaterialIsNull() {
			addCriterion("data_material is null");
			return (Criteria) this;
		}

		public Criteria andDataMaterialIsNotNull() {
			addCriterion("data_material is not null");
			return (Criteria) this;
		}

		public Criteria andDataMaterialEqualTo(String value) {
			addCriterion("data_material =", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialNotEqualTo(String value) {
			addCriterion("data_material <>", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialGreaterThan(String value) {
			addCriterion("data_material >", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialGreaterThanOrEqualTo(String value) {
			addCriterion("data_material >=", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialLessThan(String value) {
			addCriterion("data_material <", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialLessThanOrEqualTo(String value) {
			addCriterion("data_material <=", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialLike(String value) {
			addCriterion("data_material like", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialNotLike(String value) {
			addCriterion("data_material not like", value, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialIn(List<String> values) {
			addCriterion("data_material in", values, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialNotIn(List<String> values) {
			addCriterion("data_material not in", values, "dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialBetween(String value1, String value2) {
			addCriterion("data_material between", value1, value2,
					"dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMaterialNotBetween(String value1, String value2) {
			addCriterion("data_material not between", value1, value2,
					"dataMaterial");
			return (Criteria) this;
		}

		public Criteria andDataMeanIsNull() {
			addCriterion("data_mean is null");
			return (Criteria) this;
		}

		public Criteria andDataMeanIsNotNull() {
			addCriterion("data_mean is not null");
			return (Criteria) this;
		}

		public Criteria andDataMeanEqualTo(Double value) {
			addCriterion("data_mean =", value, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanNotEqualTo(Double value) {
			addCriterion("data_mean <>", value, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanGreaterThan(Double value) {
			addCriterion("data_mean >", value, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanGreaterThanOrEqualTo(Double value) {
			addCriterion("data_mean >=", value, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanLessThan(Double value) {
			addCriterion("data_mean <", value, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanLessThanOrEqualTo(Double value) {
			addCriterion("data_mean <=", value, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanIn(List<Double> values) {
			addCriterion("data_mean in", values, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanNotIn(List<Double> values) {
			addCriterion("data_mean not in", values, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanBetween(Double value1, Double value2) {
			addCriterion("data_mean between", value1, value2, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataMeanNotBetween(Double value1, Double value2) {
			addCriterion("data_mean not between", value1, value2, "dataMean");
			return (Criteria) this;
		}

		public Criteria andDataLowIsNull() {
			addCriterion("data_low is null");
			return (Criteria) this;
		}

		public Criteria andDataLowIsNotNull() {
			addCriterion("data_low is not null");
			return (Criteria) this;
		}

		public Criteria andDataLowEqualTo(Double value) {
			addCriterion("data_low =", value, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowNotEqualTo(Double value) {
			addCriterion("data_low <>", value, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowGreaterThan(Double value) {
			addCriterion("data_low >", value, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowGreaterThanOrEqualTo(Double value) {
			addCriterion("data_low >=", value, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowLessThan(Double value) {
			addCriterion("data_low <", value, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowLessThanOrEqualTo(Double value) {
			addCriterion("data_low <=", value, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowIn(List<Double> values) {
			addCriterion("data_low in", values, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowNotIn(List<Double> values) {
			addCriterion("data_low not in", values, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowBetween(Double value1, Double value2) {
			addCriterion("data_low between", value1, value2, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataLowNotBetween(Double value1, Double value2) {
			addCriterion("data_low not between", value1, value2, "dataLow");
			return (Criteria) this;
		}

		public Criteria andDataHighIsNull() {
			addCriterion("data_high is null");
			return (Criteria) this;
		}

		public Criteria andDataHighIsNotNull() {
			addCriterion("data_high is not null");
			return (Criteria) this;
		}

		public Criteria andDataHighEqualTo(Double value) {
			addCriterion("data_high =", value, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighNotEqualTo(Double value) {
			addCriterion("data_high <>", value, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighGreaterThan(Double value) {
			addCriterion("data_high >", value, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighGreaterThanOrEqualTo(Double value) {
			addCriterion("data_high >=", value, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighLessThan(Double value) {
			addCriterion("data_high <", value, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighLessThanOrEqualTo(Double value) {
			addCriterion("data_high <=", value, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighIn(List<Double> values) {
			addCriterion("data_high in", values, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighNotIn(List<Double> values) {
			addCriterion("data_high not in", values, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighBetween(Double value1, Double value2) {
			addCriterion("data_high between", value1, value2, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataHighNotBetween(Double value1, Double value2) {
			addCriterion("data_high not between", value1, value2, "dataHigh");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionIsNull() {
			addCriterion("data_precision is null");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionIsNotNull() {
			addCriterion("data_precision is not null");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionEqualTo(Double value) {
			addCriterion("data_precision =", value, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionNotEqualTo(Double value) {
			addCriterion("data_precision <>", value, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionGreaterThan(Double value) {
			addCriterion("data_precision >", value, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionGreaterThanOrEqualTo(Double value) {
			addCriterion("data_precision >=", value, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionLessThan(Double value) {
			addCriterion("data_precision <", value, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionLessThanOrEqualTo(Double value) {
			addCriterion("data_precision <=", value, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionIn(List<Double> values) {
			addCriterion("data_precision in", values, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionNotIn(List<Double> values) {
			addCriterion("data_precision not in", values, "dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionBetween(Double value1, Double value2) {
			addCriterion("data_precision between", value1, value2,
					"dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataPrecisionNotBetween(Double value1, Double value2) {
			addCriterion("data_precision not between", value1, value2,
					"dataPrecision");
			return (Criteria) this;
		}

		public Criteria andDataIntervalIsNull() {
			addCriterion("data_interval is null");
			return (Criteria) this;
		}

		public Criteria andDataIntervalIsNotNull() {
			addCriterion("data_interval is not null");
			return (Criteria) this;
		}

		public Criteria andDataIntervalEqualTo(String value) {
			addCriterion("data_interval =", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalNotEqualTo(String value) {
			addCriterion("data_interval <>", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalGreaterThan(String value) {
			addCriterion("data_interval >", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalGreaterThanOrEqualTo(String value) {
			addCriterion("data_interval >=", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalLessThan(String value) {
			addCriterion("data_interval <", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalLessThanOrEqualTo(String value) {
			addCriterion("data_interval <=", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalLike(String value) {
			addCriterion("data_interval like", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalNotLike(String value) {
			addCriterion("data_interval not like", value, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalIn(List<String> values) {
			addCriterion("data_interval in", values, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalNotIn(List<String> values) {
			addCriterion("data_interval not in", values, "dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalBetween(String value1, String value2) {
			addCriterion("data_interval between", value1, value2,
					"dataInterval");
			return (Criteria) this;
		}

		public Criteria andDataIntervalNotBetween(String value1, String value2) {
			addCriterion("data_interval not between", value1, value2,
					"dataInterval");
			return (Criteria) this;
		}

		public Criteria andRecTimeIsNull() {
			addCriterion("rec_time is null");
			return (Criteria) this;
		}

		public Criteria andRecTimeIsNotNull() {
			addCriterion("rec_time is not null");
			return (Criteria) this;
		}

		public Criteria andRecTimeEqualTo(Date value) {
			addCriterion("rec_time =", value, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeNotEqualTo(Date value) {
			addCriterion("rec_time <>", value, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeGreaterThan(Date value) {
			addCriterion("rec_time >", value, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("rec_time >=", value, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeLessThan(Date value) {
			addCriterion("rec_time <", value, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeLessThanOrEqualTo(Date value) {
			addCriterion("rec_time <=", value, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeIn(List<Date> values) {
			addCriterion("rec_time in", values, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeNotIn(List<Date> values) {
			addCriterion("rec_time not in", values, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeBetween(Date value1, Date value2) {
			addCriterion("rec_time between", value1, value2, "recTime");
			return (Criteria) this;
		}

		public Criteria andRecTimeNotBetween(Date value1, Date value2) {
			addCriterion("rec_time not between", value1, value2, "recTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table iqm_dataset
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table iqm_dataset
     *
     * @mbggenerated do_not_delete_during_merge Thu May 22 14:49:56 ICT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}