package com.healthcare.db.model;

public class ItemWithBLOBs extends Item {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.unit
	 * @mbggenerated  Wed Nov 19 08:30:10 ICT 2014
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.item_desc
	 * @mbggenerated  Wed Nov 19 08:30:10 ICT 2014
	 */
	private String itemDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.unit
	 * @return  the value of item.unit
	 * @mbggenerated  Wed Nov 19 08:30:10 ICT 2014
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.unit
	 * @param unit  the value for item.unit
	 * @mbggenerated  Wed Nov 19 08:30:10 ICT 2014
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.item_desc
	 * @return  the value of item.item_desc
	 * @mbggenerated  Wed Nov 19 08:30:10 ICT 2014
	 */
	public String getItemDesc() {
		return itemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.item_desc
	 * @param itemDesc  the value for item.item_desc
	 * @mbggenerated  Wed Nov 19 08:30:10 ICT 2014
	 */
	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}
}