package com.healthcare.db.model;

public class Item {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.item_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	private Integer itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.tr_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	private Integer trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.item_name
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	private String itemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.unit
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.item_desc
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	private String itemDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.specimen_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	private Integer specimenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column item.tg_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	private Integer tgId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.item_id
	 * @return  the value of item.item_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public Integer getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.item_id
	 * @param itemId  the value for item.item_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.tr_id
	 * @return  the value of item.tr_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public Integer getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.tr_id
	 * @param trId  the value for item.tr_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public void setTrId(Integer trId) {
		this.trId = trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.item_name
	 * @return  the value of item.item_name
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.item_name
	 * @param itemName  the value for item.item_name
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.unit
	 * @return  the value of item.unit
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.unit
	 * @param unit  the value for item.unit
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.item_desc
	 * @return  the value of item.item_desc
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public String getItemDesc() {
		return itemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.item_desc
	 * @param itemDesc  the value for item.item_desc
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.specimen_id
	 * @return  the value of item.specimen_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public Integer getSpecimenId() {
		return specimenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.specimen_id
	 * @param specimenId  the value for item.specimen_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public void setSpecimenId(Integer specimenId) {
		this.specimenId = specimenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column item.tg_id
	 * @return  the value of item.tg_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public Integer getTgId() {
		return tgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column item.tg_id
	 * @param tgId  the value for item.tg_id
	 * @mbggenerated  Wed Nov 19 08:31:17 ICT 2014
	 */
	public void setTgId(Integer tgId) {
		this.tgId = tgId;
	}
}