package com.healthcare.db.model;

import java.util.ArrayList;
import java.util.List;

public class ItemConversionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public ItemConversionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andConversionUnitIsNull() {
            addCriterion("conversion_unit is null");
            return (Criteria) this;
        }

        public Criteria andConversionUnitIsNotNull() {
            addCriterion("conversion_unit is not null");
            return (Criteria) this;
        }

        public Criteria andConversionUnitEqualTo(String value) {
            addCriterion("conversion_unit =", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitNotEqualTo(String value) {
            addCriterion("conversion_unit <>", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitGreaterThan(String value) {
            addCriterion("conversion_unit >", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitGreaterThanOrEqualTo(String value) {
            addCriterion("conversion_unit >=", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitLessThan(String value) {
            addCriterion("conversion_unit <", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitLessThanOrEqualTo(String value) {
            addCriterion("conversion_unit <=", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitLike(String value) {
            addCriterion("conversion_unit like", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitNotLike(String value) {
            addCriterion("conversion_unit not like", value, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitIn(List<String> values) {
            addCriterion("conversion_unit in", values, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitNotIn(List<String> values) {
            addCriterion("conversion_unit not in", values, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitBetween(String value1, String value2) {
            addCriterion("conversion_unit between", value1, value2, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionUnitNotBetween(String value1, String value2) {
            addCriterion("conversion_unit not between", value1, value2, "conversionUnit");
            return (Criteria) this;
        }

        public Criteria andConversionFactorIsNull() {
            addCriterion("conversion_factor is null");
            return (Criteria) this;
        }

        public Criteria andConversionFactorIsNotNull() {
            addCriterion("conversion_factor is not null");
            return (Criteria) this;
        }

        public Criteria andConversionFactorEqualTo(Float value) {
            addCriterion("conversion_factor =", value, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorNotEqualTo(Float value) {
            addCriterion("conversion_factor <>", value, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorGreaterThan(Float value) {
            addCriterion("conversion_factor >", value, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorGreaterThanOrEqualTo(Float value) {
            addCriterion("conversion_factor >=", value, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorLessThan(Float value) {
            addCriterion("conversion_factor <", value, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorLessThanOrEqualTo(Float value) {
            addCriterion("conversion_factor <=", value, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorIn(List<Float> values) {
            addCriterion("conversion_factor in", values, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorNotIn(List<Float> values) {
            addCriterion("conversion_factor not in", values, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorBetween(Float value1, Float value2) {
            addCriterion("conversion_factor between", value1, value2, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionFactorNotBetween(Float value1, Float value2) {
            addCriterion("conversion_factor not between", value1, value2, "conversionFactor");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsIsNull() {
            addCriterion("conversion_details is null");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsIsNotNull() {
            addCriterion("conversion_details is not null");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsEqualTo(String value) {
            addCriterion("conversion_details =", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsNotEqualTo(String value) {
            addCriterion("conversion_details <>", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsGreaterThan(String value) {
            addCriterion("conversion_details >", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsGreaterThanOrEqualTo(String value) {
            addCriterion("conversion_details >=", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsLessThan(String value) {
            addCriterion("conversion_details <", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsLessThanOrEqualTo(String value) {
            addCriterion("conversion_details <=", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsLike(String value) {
            addCriterion("conversion_details like", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsNotLike(String value) {
            addCriterion("conversion_details not like", value, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsIn(List<String> values) {
            addCriterion("conversion_details in", values, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsNotIn(List<String> values) {
            addCriterion("conversion_details not in", values, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsBetween(String value1, String value2) {
            addCriterion("conversion_details between", value1, value2, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andConversionDetailsNotBetween(String value1, String value2) {
            addCriterion("conversion_details not between", value1, value2, "conversionDetails");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportIsNull() {
            addCriterion("include_in_report is null");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportIsNotNull() {
            addCriterion("include_in_report is not null");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportEqualTo(Integer value) {
            addCriterion("include_in_report =", value, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportNotEqualTo(Integer value) {
            addCriterion("include_in_report <>", value, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportGreaterThan(Integer value) {
            addCriterion("include_in_report >", value, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportGreaterThanOrEqualTo(Integer value) {
            addCriterion("include_in_report >=", value, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportLessThan(Integer value) {
            addCriterion("include_in_report <", value, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportLessThanOrEqualTo(Integer value) {
            addCriterion("include_in_report <=", value, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportIn(List<Integer> values) {
            addCriterion("include_in_report in", values, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportNotIn(List<Integer> values) {
            addCriterion("include_in_report not in", values, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportBetween(Integer value1, Integer value2) {
            addCriterion("include_in_report between", value1, value2, "includeInReport");
            return (Criteria) this;
        }

        public Criteria andIncludeInReportNotBetween(Integer value1, Integer value2) {
            addCriterion("include_in_report not between", value1, value2, "includeInReport");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_conversion
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 27 08:50:25 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}