package com.healthcare.db.model;

public class ItemdataWithBLOBs extends Itemdata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemdata.item_choice
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String itemChoice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemdata.unit
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemdata.item_desc
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String itemDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemdata.item_choice
	 * @return  the value of itemdata.item_choice
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getItemChoice() {
		return itemChoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemdata.item_choice
	 * @param itemChoice  the value for itemdata.item_choice
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setItemChoice(String itemChoice) {
		this.itemChoice = itemChoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemdata.unit
	 * @return  the value of itemdata.unit
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemdata.unit
	 * @param unit  the value for itemdata.unit
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemdata.item_desc
	 * @return  the value of itemdata.item_desc
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getItemDesc() {
		return itemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemdata.item_desc
	 * @param itemDesc  the value for itemdata.item_desc
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}
}