package com.healthcare.db.model;

public class ItemRange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.item_range_id
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Integer itemRangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.item_id
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.sex
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.age_range_lb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Integer ageRangeLb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.age_range_ub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Integer ageRangeUb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.val_range_lb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Double valRangeLb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.val_range_ub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Double valRangeUb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.val_range_clb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Double valRangeClb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_range.val_range_cub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    private Double valRangeCub;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.item_range_id
     *
     * @return the value of item_range.item_range_id
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Integer getItemRangeId() {
        return itemRangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.item_range_id
     *
     * @param itemRangeId the value for item_range.item_range_id
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setItemRangeId(Integer itemRangeId) {
        this.itemRangeId = itemRangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.item_id
     *
     * @return the value of item_range.item_id
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.item_id
     *
     * @param itemId the value for item_range.item_id
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.sex
     *
     * @return the value of item_range.sex
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.sex
     *
     * @param sex the value for item_range.sex
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.age_range_lb
     *
     * @return the value of item_range.age_range_lb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Integer getAgeRangeLb() {
        return ageRangeLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.age_range_lb
     *
     * @param ageRangeLb the value for item_range.age_range_lb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setAgeRangeLb(Integer ageRangeLb) {
        this.ageRangeLb = ageRangeLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.age_range_ub
     *
     * @return the value of item_range.age_range_ub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Integer getAgeRangeUb() {
        return ageRangeUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.age_range_ub
     *
     * @param ageRangeUb the value for item_range.age_range_ub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setAgeRangeUb(Integer ageRangeUb) {
        this.ageRangeUb = ageRangeUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.val_range_lb
     *
     * @return the value of item_range.val_range_lb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Double getValRangeLb() {
        return valRangeLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.val_range_lb
     *
     * @param valRangeLb the value for item_range.val_range_lb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setValRangeLb(Double valRangeLb) {
        this.valRangeLb = valRangeLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.val_range_ub
     *
     * @return the value of item_range.val_range_ub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Double getValRangeUb() {
        return valRangeUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.val_range_ub
     *
     * @param valRangeUb the value for item_range.val_range_ub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setValRangeUb(Double valRangeUb) {
        this.valRangeUb = valRangeUb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.val_range_clb
     *
     * @return the value of item_range.val_range_clb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Double getValRangeClb() {
        return valRangeClb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.val_range_clb
     *
     * @param valRangeClb the value for item_range.val_range_clb
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setValRangeClb(Double valRangeClb) {
        this.valRangeClb = valRangeClb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_range.val_range_cub
     *
     * @return the value of item_range.val_range_cub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public Double getValRangeCub() {
        return valRangeCub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_range.val_range_cub
     *
     * @param valRangeCub the value for item_range.val_range_cub
     *
     * @mbggenerated Wed Nov 19 08:46:29 ICT 2014
     */
    public void setValRangeCub(Double valRangeCub) {
        this.valRangeCub = valRangeCub;
    }
}