package com.healthcare.db.model;

import java.util.ArrayList;
import java.util.List;

public class ItemmappingExample {
	
	
	
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public ItemmappingExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}
	
	public String getTableName(){
		return "itemmapping";
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAnalyzerIdIsNull() {
			addCriterion("analyzer_id is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNotNull() {
			addCriterion("analyzer_id is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdEqualTo(Integer value) {
			addCriterion("analyzer_id =", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotEqualTo(Integer value) {
			addCriterion("analyzer_id <>", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThan(Integer value) {
			addCriterion("analyzer_id >", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id >=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThan(Integer value) {
			addCriterion("analyzer_id <", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id <=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIn(List<Integer> values) {
			addCriterion("analyzer_id in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotIn(List<Integer> values) {
			addCriterion("analyzer_id not in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id between", value1, value2, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id not between", value1, value2,
					"analyzerId");
			return (Criteria) this;
		}

		public Criteria andItemIdIsNull() {
			addCriterion("item_id is null");
			return (Criteria) this;
		}

		public Criteria andItemIdIsNotNull() {
			addCriterion("item_id is not null");
			return (Criteria) this;
		}

		public Criteria andItemIdEqualTo(Integer value) {
			addCriterion("item_id =", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdNotEqualTo(Integer value) {
			addCriterion("item_id <>", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdGreaterThan(Integer value) {
			addCriterion("item_id >", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("item_id >=", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdLessThan(Integer value) {
			addCriterion("item_id <", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdLessThanOrEqualTo(Integer value) {
			addCriterion("item_id <=", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdIn(List<Integer> values) {
			addCriterion("item_id in", values, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdNotIn(List<Integer> values) {
			addCriterion("item_id not in", values, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdBetween(Integer value1, Integer value2) {
			addCriterion("item_id between", value1, value2, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
			addCriterion("item_id not between", value1, value2, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemInIsNull() {
			addCriterion("item_in is null");
			return (Criteria) this;
		}

		public Criteria andItemInIsNotNull() {
			addCriterion("item_in is not null");
			return (Criteria) this;
		}

		public Criteria andItemInEqualTo(String value) {
			addCriterion("item_in =", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInNotEqualTo(String value) {
			addCriterion("item_in <>", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInGreaterThan(String value) {
			addCriterion("item_in >", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInGreaterThanOrEqualTo(String value) {
			addCriterion("item_in >=", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInLessThan(String value) {
			addCriterion("item_in <", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInLessThanOrEqualTo(String value) {
			addCriterion("item_in <=", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInLike(String value) {
			addCriterion("item_in like", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInNotLike(String value) {
			addCriterion("item_in not like", value, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInIn(List<String> values) {
			addCriterion("item_in in", values, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInNotIn(List<String> values) {
			addCriterion("item_in not in", values, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInBetween(String value1, String value2) {
			addCriterion("item_in between", value1, value2, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemInNotBetween(String value1, String value2) {
			addCriterion("item_in not between", value1, value2, "itemIn");
			return (Criteria) this;
		}

		public Criteria andItemOutIsNull() {
			addCriterion("item_out is null");
			return (Criteria) this;
		}

		public Criteria andItemOutIsNotNull() {
			addCriterion("item_out is not null");
			return (Criteria) this;
		}

		public Criteria andItemOutEqualTo(String value) {
			addCriterion("item_out =", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutNotEqualTo(String value) {
			addCriterion("item_out <>", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutGreaterThan(String value) {
			addCriterion("item_out >", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutGreaterThanOrEqualTo(String value) {
			addCriterion("item_out >=", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutLessThan(String value) {
			addCriterion("item_out <", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutLessThanOrEqualTo(String value) {
			addCriterion("item_out <=", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutLike(String value) {
			addCriterion("item_out like", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutNotLike(String value) {
			addCriterion("item_out not like", value, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutIn(List<String> values) {
			addCriterion("item_out in", values, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutNotIn(List<String> values) {
			addCriterion("item_out not in", values, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutBetween(String value1, String value2) {
			addCriterion("item_out between", value1, value2, "itemOut");
			return (Criteria) this;
		}

		public Criteria andItemOutNotBetween(String value1, String value2) {
			addCriterion("item_out not between", value1, value2, "itemOut");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsIsNull() {
			addCriterion("mapping_details is null");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsIsNotNull() {
			addCriterion("mapping_details is not null");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsEqualTo(String value) {
			addCriterion("mapping_details =", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsNotEqualTo(String value) {
			addCriterion("mapping_details <>", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsGreaterThan(String value) {
			addCriterion("mapping_details >", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsGreaterThanOrEqualTo(String value) {
			addCriterion("mapping_details >=", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsLessThan(String value) {
			addCriterion("mapping_details <", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsLessThanOrEqualTo(String value) {
			addCriterion("mapping_details <=", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsLike(String value) {
			addCriterion("mapping_details like", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsNotLike(String value) {
			addCriterion("mapping_details not like", value, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsIn(List<String> values) {
			addCriterion("mapping_details in", values, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsNotIn(List<String> values) {
			addCriterion("mapping_details not in", values, "mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsBetween(String value1, String value2) {
			addCriterion("mapping_details between", value1, value2,
					"mappingDetails");
			return (Criteria) this;
		}

		public Criteria andMappingDetailsNotBetween(String value1, String value2) {
			addCriterion("mapping_details not between", value1, value2,
					"mappingDetails");
			return (Criteria) this;
		}

		public Criteria andOrderWeightIsNull() {
			addCriterion("order_weight is null");
			return (Criteria) this;
		}

		public Criteria andOrderWeightIsNotNull() {
			addCriterion("order_weight is not null");
			return (Criteria) this;
		}

		public Criteria andOrderWeightEqualTo(Integer value) {
			addCriterion("order_weight =", value, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightNotEqualTo(Integer value) {
			addCriterion("order_weight <>", value, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightGreaterThan(Integer value) {
			addCriterion("order_weight >", value, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_weight >=", value, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightLessThan(Integer value) {
			addCriterion("order_weight <", value, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightLessThanOrEqualTo(Integer value) {
			addCriterion("order_weight <=", value, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightIn(List<Integer> values) {
			addCriterion("order_weight in", values, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightNotIn(List<Integer> values) {
			addCriterion("order_weight not in", values, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightBetween(Integer value1, Integer value2) {
			addCriterion("order_weight between", value1, value2, "orderWeight");
			return (Criteria) this;
		}

		public Criteria andOrderWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("order_weight not between", value1, value2,
					"orderWeight");
			return (Criteria) this;
		}

		public Criteria andIsRequiredIsNull() {
			addCriterion("is_required is null");
			return (Criteria) this;
		}

		public Criteria andIsRequiredIsNotNull() {
			addCriterion("is_required is not null");
			return (Criteria) this;
		}

		public Criteria andIsRequiredEqualTo(Integer value) {
			addCriterion("is_required =", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredNotEqualTo(Integer value) {
			addCriterion("is_required <>", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredGreaterThan(Integer value) {
			addCriterion("is_required >", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_required >=", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredLessThan(Integer value) {
			addCriterion("is_required <", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredLessThanOrEqualTo(Integer value) {
			addCriterion("is_required <=", value, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredIn(List<Integer> values) {
			addCriterion("is_required in", values, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredNotIn(List<Integer> values) {
			addCriterion("is_required not in", values, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredBetween(Integer value1, Integer value2) {
			addCriterion("is_required between", value1, value2, "isRequired");
			return (Criteria) this;
		}

		public Criteria andIsRequiredNotBetween(Integer value1, Integer value2) {
			addCriterion("is_required not between", value1, value2,
					"isRequired");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table itemmapping
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itemmapping
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 22 09:48:39 ICT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}