package com.healthcare.db.model;

public class Itemmapping {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemmapping.analyzer_id
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	private Integer analyzerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemmapping.item_id
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	private Integer itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemmapping.item_in
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	private String itemIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemmapping.item_out
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	private String itemOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemmapping.mapping_details
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	private String mappingDetails;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemmapping.order_weight
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	private Integer orderWeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column itemmapping.is_required
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	private Integer isRequired;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemmapping.analyzer_id
	 * @return  the value of itemmapping.analyzer_id
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public Integer getAnalyzerId() {
		return analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemmapping.analyzer_id
	 * @param analyzerId  the value for itemmapping.analyzer_id
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setAnalyzerId(Integer analyzerId) {
		this.analyzerId = analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemmapping.item_id
	 * @return  the value of itemmapping.item_id
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public Integer getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemmapping.item_id
	 * @param itemId  the value for itemmapping.item_id
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemmapping.item_in
	 * @return  the value of itemmapping.item_in
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public String getItemIn() {
		return itemIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemmapping.item_in
	 * @param itemIn  the value for itemmapping.item_in
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setItemIn(String itemIn) {
		this.itemIn = itemIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemmapping.item_out
	 * @return  the value of itemmapping.item_out
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public String getItemOut() {
		return itemOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemmapping.item_out
	 * @param itemOut  the value for itemmapping.item_out
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setItemOut(String itemOut) {
		this.itemOut = itemOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemmapping.mapping_details
	 * @return  the value of itemmapping.mapping_details
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public String getMappingDetails() {
		return mappingDetails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemmapping.mapping_details
	 * @param mappingDetails  the value for itemmapping.mapping_details
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setMappingDetails(String mappingDetails) {
		this.mappingDetails = mappingDetails;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemmapping.order_weight
	 * @return  the value of itemmapping.order_weight
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public Integer getOrderWeight() {
		return orderWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemmapping.order_weight
	 * @param orderWeight  the value for itemmapping.order_weight
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setOrderWeight(Integer orderWeight) {
		this.orderWeight = orderWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column itemmapping.is_required
	 * @return  the value of itemmapping.is_required
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public Integer getIsRequired() {
		return isRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column itemmapping.is_required
	 * @param isRequired  the value for itemmapping.is_required
	 * @mbggenerated  Mon Jul 27 06:41:29 ICT 2015
	 */
	public void setIsRequired(Integer isRequired) {
		this.isRequired = isRequired;
	}
}