package com.healthcare.db.model;

public class Lot {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lot.lot_id
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	private Integer lotId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lot.tr_id
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	private Integer trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lot.lot_no
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	private String lotNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lot.lot_material
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	private String lotMaterial;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lot.lot_lv
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	private Integer lotLv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lot.lot_cuvett
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	private String lotCuvett;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lot.lot_id
	 * @return  the value of lot.lot_id
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public Integer getLotId() {
		return lotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lot.lot_id
	 * @param lotId  the value for lot.lot_id
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public void setLotId(Integer lotId) {
		this.lotId = lotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lot.tr_id
	 * @return  the value of lot.tr_id
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public Integer getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lot.tr_id
	 * @param trId  the value for lot.tr_id
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public void setTrId(Integer trId) {
		this.trId = trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lot.lot_no
	 * @return  the value of lot.lot_no
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public String getLotNo() {
		return lotNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lot.lot_no
	 * @param lotNo  the value for lot.lot_no
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public void setLotNo(String lotNo) {
		this.lotNo = lotNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lot.lot_material
	 * @return  the value of lot.lot_material
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public String getLotMaterial() {
		return lotMaterial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lot.lot_material
	 * @param lotMaterial  the value for lot.lot_material
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public void setLotMaterial(String lotMaterial) {
		this.lotMaterial = lotMaterial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lot.lot_lv
	 * @return  the value of lot.lot_lv
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public Integer getLotLv() {
		return lotLv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lot.lot_lv
	 * @param lotLv  the value for lot.lot_lv
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public void setLotLv(Integer lotLv) {
		this.lotLv = lotLv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lot.lot_cuvett
	 * @return  the value of lot.lot_cuvett
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public String getLotCuvett() {
		return lotCuvett;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lot.lot_cuvett
	 * @param lotCuvett  the value for lot.lot_cuvett
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	public void setLotCuvett(String lotCuvett) {
		this.lotCuvett = lotCuvett;
	}
}