package com.healthcare.db.model;

public class NewtestitemWithBLOBs extends Newtestitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newtestitem.value
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newtestitem.comment
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newtestitem.errorcode
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    private String errorcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newtestitem.value
     *
     * @return the value of newtestitem.value
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newtestitem.value
     *
     * @param value the value for newtestitem.value
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newtestitem.comment
     *
     * @return the value of newtestitem.comment
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newtestitem.comment
     *
     * @param comment the value for newtestitem.comment
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newtestitem.errorcode
     *
     * @return the value of newtestitem.errorcode
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    public String getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newtestitem.errorcode
     *
     * @param errorcode the value for newtestitem.errorcode
     *
     * @mbggenerated Tue Apr 01 20:13:19 ICT 2014
     */
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }
}