package com.healthcare.db.model;

import java.util.Date;

public class Newtest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.test_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.labid
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String labid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.analyzer_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer analyzerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.ward_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer wardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.staff_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.staff2_code
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String staff2Code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.p_hn
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String pHn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.status1_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Date status1Dt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.status2_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Date status2Dt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.status3_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Date status3Dt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.status4_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Date status4Dt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.status5_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Date status5Dt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.status6_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Date status6Dt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.bill
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String bill;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.status
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.p_type
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String pType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.vn
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String vn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.price_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer priceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.pathhtml
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String pathhtml;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtest.comment
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.test_id
	 * @return  the value of newtest.test_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.test_id
	 * @param testId  the value for newtest.test_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.labid
	 * @return  the value of newtest.labid
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getLabid() {
		return labid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.labid
	 * @param labid  the value for newtest.labid
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setLabid(String labid) {
		this.labid = labid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.analyzer_id
	 * @return  the value of newtest.analyzer_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getAnalyzerId() {
		return analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.analyzer_id
	 * @param analyzerId  the value for newtest.analyzer_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setAnalyzerId(Integer analyzerId) {
		this.analyzerId = analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.ward_id
	 * @return  the value of newtest.ward_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getWardId() {
		return wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.ward_id
	 * @param wardId  the value for newtest.ward_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setWardId(Integer wardId) {
		this.wardId = wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.staff_id
	 * @return  the value of newtest.staff_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.staff_id
	 * @param staffId  the value for newtest.staff_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.staff2_code
	 * @return  the value of newtest.staff2_code
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getStaff2Code() {
		return staff2Code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.staff2_code
	 * @param staff2Code  the value for newtest.staff2_code
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStaff2Code(String staff2Code) {
		this.staff2Code = staff2Code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.p_hn
	 * @return  the value of newtest.p_hn
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getpHn() {
		return pHn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.p_hn
	 * @param pHn  the value for newtest.p_hn
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setpHn(String pHn) {
		this.pHn = pHn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.status1_dt
	 * @return  the value of newtest.status1_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Date getStatus1Dt() {
		return status1Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.status1_dt
	 * @param status1Dt  the value for newtest.status1_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStatus1Dt(Date status1Dt) {
		this.status1Dt = status1Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.status2_dt
	 * @return  the value of newtest.status2_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Date getStatus2Dt() {
		return status2Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.status2_dt
	 * @param status2Dt  the value for newtest.status2_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStatus2Dt(Date status2Dt) {
		this.status2Dt = status2Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.status3_dt
	 * @return  the value of newtest.status3_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Date getStatus3Dt() {
		return status3Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.status3_dt
	 * @param status3Dt  the value for newtest.status3_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStatus3Dt(Date status3Dt) {
		this.status3Dt = status3Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.status4_dt
	 * @return  the value of newtest.status4_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Date getStatus4Dt() {
		return status4Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.status4_dt
	 * @param status4Dt  the value for newtest.status4_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStatus4Dt(Date status4Dt) {
		this.status4Dt = status4Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.status5_dt
	 * @return  the value of newtest.status5_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Date getStatus5Dt() {
		return status5Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.status5_dt
	 * @param status5Dt  the value for newtest.status5_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStatus5Dt(Date status5Dt) {
		this.status5Dt = status5Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.status6_dt
	 * @return  the value of newtest.status6_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Date getStatus6Dt() {
		return status6Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.status6_dt
	 * @param status6Dt  the value for newtest.status6_dt
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStatus6Dt(Date status6Dt) {
		this.status6Dt = status6Dt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.bill
	 * @return  the value of newtest.bill
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getBill() {
		return bill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.bill
	 * @param bill  the value for newtest.bill
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setBill(String bill) {
		this.bill = bill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.status
	 * @return  the value of newtest.status
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.status
	 * @param status  the value for newtest.status
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.p_type
	 * @return  the value of newtest.p_type
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getpType() {
		return pType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.p_type
	 * @param pType  the value for newtest.p_type
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setpType(String pType) {
		this.pType = pType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.vn
	 * @return  the value of newtest.vn
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getVn() {
		return vn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.vn
	 * @param vn  the value for newtest.vn
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setVn(String vn) {
		this.vn = vn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.price_id
	 * @return  the value of newtest.price_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getPriceId() {
		return priceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.price_id
	 * @param priceId  the value for newtest.price_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setPriceId(Integer priceId) {
		this.priceId = priceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.pathhtml
	 * @return  the value of newtest.pathhtml
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getPathhtml() {
		return pathhtml;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.pathhtml
	 * @param pathhtml  the value for newtest.pathhtml
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setPathhtml(String pathhtml) {
		this.pathhtml = pathhtml;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtest.comment
	 * @return  the value of newtest.comment
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtest.comment
	 * @param comment  the value for newtest.comment
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}