package com.healthcare.db.model;

public class PatientWithBLOBs extends Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_fname
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    private String pFname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_lname
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    private String pLname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_address
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    private String pAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_email
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    private String pEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_fname
     *
     * @return the value of patient.p_fname
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public String getpFname() {
        return pFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_fname
     *
     * @param pFname the value for patient.p_fname
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public void setpFname(String pFname) {
        this.pFname = pFname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_lname
     *
     * @return the value of patient.p_lname
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public String getpLname() {
        return pLname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_lname
     *
     * @param pLname the value for patient.p_lname
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public void setpLname(String pLname) {
        this.pLname = pLname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_address
     *
     * @return the value of patient.p_address
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public String getpAddress() {
        return pAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_address
     *
     * @param pAddress the value for patient.p_address
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public void setpAddress(String pAddress) {
        this.pAddress = pAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_email
     *
     * @return the value of patient.p_email
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public String getpEmail() {
        return pEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_email
     *
     * @param pEmail the value for patient.p_email
     *
     * @mbggenerated Mon Nov 17 20:01:43 ICT 2014
     */
    public void setpEmail(String pEmail) {
        this.pEmail = pEmail;
    }
}