package com.healthcare.db.model;

import java.util.Date;

public class Qc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.qc_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private Integer qcId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.tr_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private Integer trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.qc_dt
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private Date qcDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.analyzer_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private Integer analyzerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.lot_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private Integer lotId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.ward_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private Integer wardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.qc_status
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private Integer qcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.staff_code
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private String staffCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qc.comment
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.qc_id
	 * @return  the value of qc.qc_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Integer getQcId() {
		return qcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.qc_id
	 * @param qcId  the value for qc.qc_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setQcId(Integer qcId) {
		this.qcId = qcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.tr_id
	 * @return  the value of qc.tr_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Integer getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.tr_id
	 * @param trId  the value for qc.tr_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setTrId(Integer trId) {
		this.trId = trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.qc_dt
	 * @return  the value of qc.qc_dt
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Date getQcDt() {
		return qcDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.qc_dt
	 * @param qcDt  the value for qc.qc_dt
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setQcDt(Date qcDt) {
		this.qcDt = qcDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.analyzer_id
	 * @return  the value of qc.analyzer_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Integer getAnalyzerId() {
		return analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.analyzer_id
	 * @param analyzerId  the value for qc.analyzer_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setAnalyzerId(Integer analyzerId) {
		this.analyzerId = analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.lot_id
	 * @return  the value of qc.lot_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Integer getLotId() {
		return lotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.lot_id
	 * @param lotId  the value for qc.lot_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setLotId(Integer lotId) {
		this.lotId = lotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.ward_id
	 * @return  the value of qc.ward_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Integer getWardId() {
		return wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.ward_id
	 * @param wardId  the value for qc.ward_id
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setWardId(Integer wardId) {
		this.wardId = wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.qc_status
	 * @return  the value of qc.qc_status
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Integer getQcStatus() {
		return qcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.qc_status
	 * @param qcStatus  the value for qc.qc_status
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setQcStatus(Integer qcStatus) {
		this.qcStatus = qcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.staff_code
	 * @return  the value of qc.staff_code
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public String getStaffCode() {
		return staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.staff_code
	 * @param staffCode  the value for qc.staff_code
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qc.comment
	 * @return  the value of qc.comment
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qc.comment
	 * @param comment  the value for qc.comment
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}