package com.healthcare.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QcExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public QcExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andQcIdIsNull() {
			addCriterion("qc_id is null");
			return (Criteria) this;
		}

		public Criteria andQcIdIsNotNull() {
			addCriterion("qc_id is not null");
			return (Criteria) this;
		}

		public Criteria andQcIdEqualTo(Integer value) {
			addCriterion("qc_id =", value, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdNotEqualTo(Integer value) {
			addCriterion("qc_id <>", value, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdGreaterThan(Integer value) {
			addCriterion("qc_id >", value, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("qc_id >=", value, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdLessThan(Integer value) {
			addCriterion("qc_id <", value, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdLessThanOrEqualTo(Integer value) {
			addCriterion("qc_id <=", value, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdIn(List<Integer> values) {
			addCriterion("qc_id in", values, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdNotIn(List<Integer> values) {
			addCriterion("qc_id not in", values, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdBetween(Integer value1, Integer value2) {
			addCriterion("qc_id between", value1, value2, "qcId");
			return (Criteria) this;
		}

		public Criteria andQcIdNotBetween(Integer value1, Integer value2) {
			addCriterion("qc_id not between", value1, value2, "qcId");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNull() {
			addCriterion("tr_id is null");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNotNull() {
			addCriterion("tr_id is not null");
			return (Criteria) this;
		}

		public Criteria andTrIdEqualTo(Integer value) {
			addCriterion("tr_id =", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotEqualTo(Integer value) {
			addCriterion("tr_id <>", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThan(Integer value) {
			addCriterion("tr_id >", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("tr_id >=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThan(Integer value) {
			addCriterion("tr_id <", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThanOrEqualTo(Integer value) {
			addCriterion("tr_id <=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdIn(List<Integer> values) {
			addCriterion("tr_id in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotIn(List<Integer> values) {
			addCriterion("tr_id not in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdBetween(Integer value1, Integer value2) {
			addCriterion("tr_id between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotBetween(Integer value1, Integer value2) {
			addCriterion("tr_id not between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andQcDtIsNull() {
			addCriterion("qc_dt is null");
			return (Criteria) this;
		}

		public Criteria andQcDtIsNotNull() {
			addCriterion("qc_dt is not null");
			return (Criteria) this;
		}

		public Criteria andQcDtEqualTo(Date value) {
			addCriterion("qc_dt =", value, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtNotEqualTo(Date value) {
			addCriterion("qc_dt <>", value, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtGreaterThan(Date value) {
			addCriterion("qc_dt >", value, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtGreaterThanOrEqualTo(Date value) {
			addCriterion("qc_dt >=", value, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtLessThan(Date value) {
			addCriterion("qc_dt <", value, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtLessThanOrEqualTo(Date value) {
			addCriterion("qc_dt <=", value, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtIn(List<Date> values) {
			addCriterion("qc_dt in", values, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtNotIn(List<Date> values) {
			addCriterion("qc_dt not in", values, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtBetween(Date value1, Date value2) {
			addCriterion("qc_dt between", value1, value2, "qcDt");
			return (Criteria) this;
		}

		public Criteria andQcDtNotBetween(Date value1, Date value2) {
			addCriterion("qc_dt not between", value1, value2, "qcDt");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNull() {
			addCriterion("analyzer_id is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNotNull() {
			addCriterion("analyzer_id is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdEqualTo(Integer value) {
			addCriterion("analyzer_id =", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotEqualTo(Integer value) {
			addCriterion("analyzer_id <>", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThan(Integer value) {
			addCriterion("analyzer_id >", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id >=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThan(Integer value) {
			addCriterion("analyzer_id <", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id <=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIn(List<Integer> values) {
			addCriterion("analyzer_id in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotIn(List<Integer> values) {
			addCriterion("analyzer_id not in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id between", value1, value2, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id not between", value1, value2,
					"analyzerId");
			return (Criteria) this;
		}

		public Criteria andLotIdIsNull() {
			addCriterion("lot_id is null");
			return (Criteria) this;
		}

		public Criteria andLotIdIsNotNull() {
			addCriterion("lot_id is not null");
			return (Criteria) this;
		}

		public Criteria andLotIdEqualTo(Integer value) {
			addCriterion("lot_id =", value, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdNotEqualTo(Integer value) {
			addCriterion("lot_id <>", value, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdGreaterThan(Integer value) {
			addCriterion("lot_id >", value, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("lot_id >=", value, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdLessThan(Integer value) {
			addCriterion("lot_id <", value, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdLessThanOrEqualTo(Integer value) {
			addCriterion("lot_id <=", value, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdIn(List<Integer> values) {
			addCriterion("lot_id in", values, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdNotIn(List<Integer> values) {
			addCriterion("lot_id not in", values, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdBetween(Integer value1, Integer value2) {
			addCriterion("lot_id between", value1, value2, "lotId");
			return (Criteria) this;
		}

		public Criteria andLotIdNotBetween(Integer value1, Integer value2) {
			addCriterion("lot_id not between", value1, value2, "lotId");
			return (Criteria) this;
		}

		public Criteria andWardIdIsNull() {
			addCriterion("ward_id is null");
			return (Criteria) this;
		}

		public Criteria andWardIdIsNotNull() {
			addCriterion("ward_id is not null");
			return (Criteria) this;
		}

		public Criteria andWardIdEqualTo(Integer value) {
			addCriterion("ward_id =", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotEqualTo(Integer value) {
			addCriterion("ward_id <>", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdGreaterThan(Integer value) {
			addCriterion("ward_id >", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ward_id >=", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdLessThan(Integer value) {
			addCriterion("ward_id <", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdLessThanOrEqualTo(Integer value) {
			addCriterion("ward_id <=", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdIn(List<Integer> values) {
			addCriterion("ward_id in", values, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotIn(List<Integer> values) {
			addCriterion("ward_id not in", values, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdBetween(Integer value1, Integer value2) {
			addCriterion("ward_id between", value1, value2, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ward_id not between", value1, value2, "wardId");
			return (Criteria) this;
		}

		public Criteria andQcStatusIsNull() {
			addCriterion("qc_status is null");
			return (Criteria) this;
		}

		public Criteria andQcStatusIsNotNull() {
			addCriterion("qc_status is not null");
			return (Criteria) this;
		}

		public Criteria andQcStatusEqualTo(Integer value) {
			addCriterion("qc_status =", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusNotEqualTo(Integer value) {
			addCriterion("qc_status <>", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusGreaterThan(Integer value) {
			addCriterion("qc_status >", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("qc_status >=", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusLessThan(Integer value) {
			addCriterion("qc_status <", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusLessThanOrEqualTo(Integer value) {
			addCriterion("qc_status <=", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusIn(List<Integer> values) {
			addCriterion("qc_status in", values, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusNotIn(List<Integer> values) {
			addCriterion("qc_status not in", values, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusBetween(Integer value1, Integer value2) {
			addCriterion("qc_status between", value1, value2, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("qc_status not between", value1, value2, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andStaffCodeIsNull() {
			addCriterion("staff_code is null");
			return (Criteria) this;
		}

		public Criteria andStaffCodeIsNotNull() {
			addCriterion("staff_code is not null");
			return (Criteria) this;
		}

		public Criteria andStaffCodeEqualTo(String value) {
			addCriterion("staff_code =", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotEqualTo(String value) {
			addCriterion("staff_code <>", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeGreaterThan(String value) {
			addCriterion("staff_code >", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeGreaterThanOrEqualTo(String value) {
			addCriterion("staff_code >=", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeLessThan(String value) {
			addCriterion("staff_code <", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeLessThanOrEqualTo(String value) {
			addCriterion("staff_code <=", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeLike(String value) {
			addCriterion("staff_code like", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotLike(String value) {
			addCriterion("staff_code not like", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeIn(List<String> values) {
			addCriterion("staff_code in", values, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotIn(List<String> values) {
			addCriterion("staff_code not in", values, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeBetween(String value1, String value2) {
			addCriterion("staff_code between", value1, value2, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotBetween(String value1, String value2) {
			addCriterion("staff_code not between", value1, value2, "staffCode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qc
	 * @mbggenerated  Wed Oct 15 12:29:12 ICT 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qc
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 25 08:43:14 ICT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}