package com.healthcare.db.model;

public class Systemconfigure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemconfigure.conf_id
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    private Integer confId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemconfigure.prarameter_name
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    private String prarameterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemconfigure.parameter_value
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    private String parameterValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemconfigure.conf_id
     *
     * @return the value of systemconfigure.conf_id
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    public Integer getConfId() {
        return confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemconfigure.conf_id
     *
     * @param confId the value for systemconfigure.conf_id
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    public void setConfId(Integer confId) {
        this.confId = confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemconfigure.prarameter_name
     *
     * @return the value of systemconfigure.prarameter_name
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    public String getPrarameterName() {
        return prarameterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemconfigure.prarameter_name
     *
     * @param prarameterName the value for systemconfigure.prarameter_name
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    public void setPrarameterName(String prarameterName) {
        this.prarameterName = prarameterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemconfigure.parameter_value
     *
     * @return the value of systemconfigure.parameter_value
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    public String getParameterValue() {
        return parameterValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemconfigure.parameter_value
     *
     * @param parameterValue the value for systemconfigure.parameter_value
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    public void setParameterValue(String parameterValue) {
        this.parameterValue = parameterValue;
    }
}