package com.healthcare.db.model;

import java.util.Date;

public class Test_ {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Integer testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.tr_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Integer trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Date testDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.dock_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Date dockDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.analyzer_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Integer analyzerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.ward_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Integer wardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.staff_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.staff_code
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String staffCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.p_hn
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String pHn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.status
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.comment
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.labid
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String labid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.bill_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String billId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.order_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.enc_type
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String encType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.enc_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String encId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.update_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Date updateDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.update_by
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private Integer updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.rec_by_command
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	private String recByCommand;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_id
	 * @return  the value of test.test_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Integer getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_id
	 * @param testId  the value for test.test_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.tr_id
	 * @return  the value of test.tr_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Integer getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.tr_id
	 * @param trId  the value for test.tr_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setTrId(Integer trId) {
		this.trId = trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_dt
	 * @return  the value of test.test_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Date getTestDt() {
		return testDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_dt
	 * @param testDt  the value for test.test_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setTestDt(Date testDt) {
		this.testDt = testDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.dock_dt
	 * @return  the value of test.dock_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Date getDockDt() {
		return dockDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.dock_dt
	 * @param dockDt  the value for test.dock_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setDockDt(Date dockDt) {
		this.dockDt = dockDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.analyzer_id
	 * @return  the value of test.analyzer_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Integer getAnalyzerId() {
		return analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.analyzer_id
	 * @param analyzerId  the value for test.analyzer_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setAnalyzerId(Integer analyzerId) {
		this.analyzerId = analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.ward_id
	 * @return  the value of test.ward_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Integer getWardId() {
		return wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.ward_id
	 * @param wardId  the value for test.ward_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setWardId(Integer wardId) {
		this.wardId = wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.staff_id
	 * @return  the value of test.staff_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.staff_id
	 * @param staffId  the value for test.staff_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.staff_code
	 * @return  the value of test.staff_code
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getStaffCode() {
		return staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.staff_code
	 * @param staffCode  the value for test.staff_code
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.p_hn
	 * @return  the value of test.p_hn
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getpHn() {
		return pHn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.p_hn
	 * @param pHn  the value for test.p_hn
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setpHn(String pHn) {
		this.pHn = pHn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.status
	 * @return  the value of test.status
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.status
	 * @param status  the value for test.status
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.comment
	 * @return  the value of test.comment
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.comment
	 * @param comment  the value for test.comment
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.labid
	 * @return  the value of test.labid
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getLabid() {
		return labid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.labid
	 * @param labid  the value for test.labid
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setLabid(String labid) {
		this.labid = labid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.bill_id
	 * @return  the value of test.bill_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getBillId() {
		return billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.bill_id
	 * @param billId  the value for test.bill_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setBillId(String billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.order_id
	 * @return  the value of test.order_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.order_id
	 * @param orderId  the value for test.order_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.enc_type
	 * @return  the value of test.enc_type
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getEncType() {
		return encType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.enc_type
	 * @param encType  the value for test.enc_type
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setEncType(String encType) {
		this.encType = encType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.enc_id
	 * @return  the value of test.enc_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getEncId() {
		return encId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.enc_id
	 * @param encId  the value for test.enc_id
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setEncId(String encId) {
		this.encId = encId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.update_dt
	 * @return  the value of test.update_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Date getUpdateDt() {
		return updateDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.update_dt
	 * @param updateDt  the value for test.update_dt
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.update_by
	 * @return  the value of test.update_by
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public Integer getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.update_by
	 * @param updateBy  the value for test.update_by
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.rec_by_command
	 * @return  the value of test.rec_by_command
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public String getRecByCommand() {
		return recByCommand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.rec_by_command
	 * @param recByCommand  the value for test.rec_by_command
	 * @mbggenerated  Mon Dec 15 23:30:49 ICT 2014
	 */
	public void setRecByCommand(String recByCommand) {
		this.recByCommand = recByCommand;
	}
}