package com.healthcare.db.model;

public class TestitemWithBLOBs extends Testitem {
	
	private String tableName;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitem.value
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitem.comment
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitem.errorcode
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    private String errorcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitem.value
     *
     * @return the value of testitem.value
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitem.value
     *
     * @param value the value for testitem.value
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitem.comment
     *
     * @return the value of testitem.comment
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitem.comment
     *
     * @param comment the value for testitem.comment
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitem.errorcode
     *
     * @return the value of testitem.errorcode
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    public String getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitem.errorcode
     *
     * @param errorcode the value for testitem.errorcode
     *
     * @mbggenerated Mon Sep 22 09:48:39 ICT 2014
     */
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }
    
    
}