package com.healthcare.db.model;

import java.util.Date;

public class TestChangeRevisions extends TestChangeRevisionsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.tr_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.test_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Date testDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.dock_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Date dockDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.analyzer_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer analyzerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.ward_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer wardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.staff_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.staff_code
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String staffCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.p_hn
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String pHn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.status
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.labid
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String labid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.bill_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String billId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.order_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.enc_type
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String encType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.enc_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String encId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.update_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Date updateDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.update_by
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.rec_by_command
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String recByCommand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.p_loc_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer pLocId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.is_edited
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer isEdited;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.isprm
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String isprm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.ifcomment
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String ifcomment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.error_code
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer errorCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.is_ack
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer isAck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.exec_time
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Date execTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.retry_count
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer retryCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.specimen_type
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String specimenType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.comment
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.tr_id
	 * @return  the value of test_change_revisions.tr_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.tr_id
	 * @param trId  the value for test_change_revisions.tr_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setTrId(Integer trId) {
		this.trId = trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.test_dt
	 * @return  the value of test_change_revisions.test_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Date getTestDt() {
		return testDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.test_dt
	 * @param testDt  the value for test_change_revisions.test_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setTestDt(Date testDt) {
		this.testDt = testDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.dock_dt
	 * @return  the value of test_change_revisions.dock_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Date getDockDt() {
		return dockDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.dock_dt
	 * @param dockDt  the value for test_change_revisions.dock_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setDockDt(Date dockDt) {
		this.dockDt = dockDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.analyzer_id
	 * @return  the value of test_change_revisions.analyzer_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getAnalyzerId() {
		return analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.analyzer_id
	 * @param analyzerId  the value for test_change_revisions.analyzer_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setAnalyzerId(Integer analyzerId) {
		this.analyzerId = analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.ward_id
	 * @return  the value of test_change_revisions.ward_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getWardId() {
		return wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.ward_id
	 * @param wardId  the value for test_change_revisions.ward_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setWardId(Integer wardId) {
		this.wardId = wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.staff_id
	 * @return  the value of test_change_revisions.staff_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.staff_id
	 * @param staffId  the value for test_change_revisions.staff_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.staff_code
	 * @return  the value of test_change_revisions.staff_code
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getStaffCode() {
		return staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.staff_code
	 * @param staffCode  the value for test_change_revisions.staff_code
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.p_hn
	 * @return  the value of test_change_revisions.p_hn
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getpHn() {
		return pHn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.p_hn
	 * @param pHn  the value for test_change_revisions.p_hn
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setpHn(String pHn) {
		this.pHn = pHn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.status
	 * @return  the value of test_change_revisions.status
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.status
	 * @param status  the value for test_change_revisions.status
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.labid
	 * @return  the value of test_change_revisions.labid
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getLabid() {
		return labid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.labid
	 * @param labid  the value for test_change_revisions.labid
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setLabid(String labid) {
		this.labid = labid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.bill_id
	 * @return  the value of test_change_revisions.bill_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getBillId() {
		return billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.bill_id
	 * @param billId  the value for test_change_revisions.bill_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setBillId(String billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.order_id
	 * @return  the value of test_change_revisions.order_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.order_id
	 * @param orderId  the value for test_change_revisions.order_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.enc_type
	 * @return  the value of test_change_revisions.enc_type
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getEncType() {
		return encType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.enc_type
	 * @param encType  the value for test_change_revisions.enc_type
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setEncType(String encType) {
		this.encType = encType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.enc_id
	 * @return  the value of test_change_revisions.enc_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getEncId() {
		return encId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.enc_id
	 * @param encId  the value for test_change_revisions.enc_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setEncId(String encId) {
		this.encId = encId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.update_dt
	 * @return  the value of test_change_revisions.update_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Date getUpdateDt() {
		return updateDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.update_dt
	 * @param updateDt  the value for test_change_revisions.update_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.update_by
	 * @return  the value of test_change_revisions.update_by
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.update_by
	 * @param updateBy  the value for test_change_revisions.update_by
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.rec_by_command
	 * @return  the value of test_change_revisions.rec_by_command
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getRecByCommand() {
		return recByCommand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.rec_by_command
	 * @param recByCommand  the value for test_change_revisions.rec_by_command
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setRecByCommand(String recByCommand) {
		this.recByCommand = recByCommand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.p_loc_id
	 * @return  the value of test_change_revisions.p_loc_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getpLocId() {
		return pLocId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.p_loc_id
	 * @param pLocId  the value for test_change_revisions.p_loc_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setpLocId(Integer pLocId) {
		this.pLocId = pLocId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.is_edited
	 * @return  the value of test_change_revisions.is_edited
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getIsEdited() {
		return isEdited;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.is_edited
	 * @param isEdited  the value for test_change_revisions.is_edited
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setIsEdited(Integer isEdited) {
		this.isEdited = isEdited;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.isprm
	 * @return  the value of test_change_revisions.isprm
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getIsprm() {
		return isprm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.isprm
	 * @param isprm  the value for test_change_revisions.isprm
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setIsprm(String isprm) {
		this.isprm = isprm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.ifcomment
	 * @return  the value of test_change_revisions.ifcomment
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getIfcomment() {
		return ifcomment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.ifcomment
	 * @param ifcomment  the value for test_change_revisions.ifcomment
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setIfcomment(String ifcomment) {
		this.ifcomment = ifcomment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.error_code
	 * @return  the value of test_change_revisions.error_code
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getErrorCode() {
		return errorCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.error_code
	 * @param errorCode  the value for test_change_revisions.error_code
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.is_ack
	 * @return  the value of test_change_revisions.is_ack
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getIsAck() {
		return isAck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.is_ack
	 * @param isAck  the value for test_change_revisions.is_ack
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setIsAck(Integer isAck) {
		this.isAck = isAck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.exec_time
	 * @return  the value of test_change_revisions.exec_time
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Date getExecTime() {
		return execTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.exec_time
	 * @param execTime  the value for test_change_revisions.exec_time
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setExecTime(Date execTime) {
		this.execTime = execTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.retry_count
	 * @return  the value of test_change_revisions.retry_count
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getRetryCount() {
		return retryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.retry_count
	 * @param retryCount  the value for test_change_revisions.retry_count
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setRetryCount(Integer retryCount) {
		this.retryCount = retryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.specimen_type
	 * @return  the value of test_change_revisions.specimen_type
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getSpecimenType() {
		return specimenType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.specimen_type
	 * @param specimenType  the value for test_change_revisions.specimen_type
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setSpecimenType(String specimenType) {
		this.specimenType = specimenType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.comment
	 * @return  the value of test_change_revisions.comment
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.comment
	 * @param comment  the value for test_change_revisions.comment
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}