package com.healthcare.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public TestExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTestIdIsNull() {
			addCriterion("test_id is null");
			return (Criteria) this;
		}

		public Criteria andTestIdIsNotNull() {
			addCriterion("test_id is not null");
			return (Criteria) this;
		}

		public Criteria andTestIdEqualTo(Integer value) {
			addCriterion("test_id =", value, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdNotEqualTo(Integer value) {
			addCriterion("test_id <>", value, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdGreaterThan(Integer value) {
			addCriterion("test_id >", value, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("test_id >=", value, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdLessThan(Integer value) {
			addCriterion("test_id <", value, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdLessThanOrEqualTo(Integer value) {
			addCriterion("test_id <=", value, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdIn(List<Integer> values) {
			addCriterion("test_id in", values, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdNotIn(List<Integer> values) {
			addCriterion("test_id not in", values, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdBetween(Integer value1, Integer value2) {
			addCriterion("test_id between", value1, value2, "testId");
			return (Criteria) this;
		}

		public Criteria andTestIdNotBetween(Integer value1, Integer value2) {
			addCriterion("test_id not between", value1, value2, "testId");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNull() {
			addCriterion("tr_id is null");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNotNull() {
			addCriterion("tr_id is not null");
			return (Criteria) this;
		}

		public Criteria andTrIdEqualTo(Integer value) {
			addCriterion("tr_id =", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotEqualTo(Integer value) {
			addCriterion("tr_id <>", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThan(Integer value) {
			addCriterion("tr_id >", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("tr_id >=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThan(Integer value) {
			addCriterion("tr_id <", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThanOrEqualTo(Integer value) {
			addCriterion("tr_id <=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdIn(List<Integer> values) {
			addCriterion("tr_id in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotIn(List<Integer> values) {
			addCriterion("tr_id not in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdBetween(Integer value1, Integer value2) {
			addCriterion("tr_id between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotBetween(Integer value1, Integer value2) {
			addCriterion("tr_id not between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andTestDtIsNull() {
			addCriterion("test_dt is null");
			return (Criteria) this;
		}

		public Criteria andTestDtIsNotNull() {
			addCriterion("test_dt is not null");
			return (Criteria) this;
		}

		public Criteria andTestDtEqualTo(Date value) {
			addCriterion("test_dt =", value, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtNotEqualTo(Date value) {
			addCriterion("test_dt <>", value, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtGreaterThan(Date value) {
			addCriterion("test_dt >", value, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtGreaterThanOrEqualTo(Date value) {
			addCriterion("test_dt >=", value, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtLessThan(Date value) {
			addCriterion("test_dt <", value, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtLessThanOrEqualTo(Date value) {
			addCriterion("test_dt <=", value, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtIn(List<Date> values) {
			addCriterion("test_dt in", values, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtNotIn(List<Date> values) {
			addCriterion("test_dt not in", values, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtBetween(Date value1, Date value2) {
			addCriterion("test_dt between", value1, value2, "testDt");
			return (Criteria) this;
		}

		public Criteria andTestDtNotBetween(Date value1, Date value2) {
			addCriterion("test_dt not between", value1, value2, "testDt");
			return (Criteria) this;
		}

		public Criteria andDockDtIsNull() {
			addCriterion("dock_dt is null");
			return (Criteria) this;
		}

		public Criteria andDockDtIsNotNull() {
			addCriterion("dock_dt is not null");
			return (Criteria) this;
		}

		public Criteria andDockDtEqualTo(Date value) {
			addCriterion("dock_dt =", value, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtNotEqualTo(Date value) {
			addCriterion("dock_dt <>", value, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtGreaterThan(Date value) {
			addCriterion("dock_dt >", value, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtGreaterThanOrEqualTo(Date value) {
			addCriterion("dock_dt >=", value, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtLessThan(Date value) {
			addCriterion("dock_dt <", value, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtLessThanOrEqualTo(Date value) {
			addCriterion("dock_dt <=", value, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtIn(List<Date> values) {
			addCriterion("dock_dt in", values, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtNotIn(List<Date> values) {
			addCriterion("dock_dt not in", values, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtBetween(Date value1, Date value2) {
			addCriterion("dock_dt between", value1, value2, "dockDt");
			return (Criteria) this;
		}

		public Criteria andDockDtNotBetween(Date value1, Date value2) {
			addCriterion("dock_dt not between", value1, value2, "dockDt");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNull() {
			addCriterion("analyzer_id is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNotNull() {
			addCriterion("analyzer_id is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdEqualTo(Integer value) {
			addCriterion("analyzer_id =", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotEqualTo(Integer value) {
			addCriterion("analyzer_id <>", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThan(Integer value) {
			addCriterion("analyzer_id >", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id >=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThan(Integer value) {
			addCriterion("analyzer_id <", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id <=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIn(List<Integer> values) {
			addCriterion("analyzer_id in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotIn(List<Integer> values) {
			addCriterion("analyzer_id not in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id between", value1, value2, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id not between", value1, value2,
					"analyzerId");
			return (Criteria) this;
		}

		public Criteria andWardIdIsNull() {
			addCriterion("ward_id is null");
			return (Criteria) this;
		}

		public Criteria andWardIdIsNotNull() {
			addCriterion("ward_id is not null");
			return (Criteria) this;
		}

		public Criteria andWardIdEqualTo(Integer value) {
			addCriterion("ward_id =", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotEqualTo(Integer value) {
			addCriterion("ward_id <>", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdGreaterThan(Integer value) {
			addCriterion("ward_id >", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ward_id >=", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdLessThan(Integer value) {
			addCriterion("ward_id <", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdLessThanOrEqualTo(Integer value) {
			addCriterion("ward_id <=", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdIn(List<Integer> values) {
			addCriterion("ward_id in", values, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotIn(List<Integer> values) {
			addCriterion("ward_id not in", values, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdBetween(Integer value1, Integer value2) {
			addCriterion("ward_id between", value1, value2, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ward_id not between", value1, value2, "wardId");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNull() {
			addCriterion("staff_id is null");
			return (Criteria) this;
		}

		public Criteria andStaffIdIsNotNull() {
			addCriterion("staff_id is not null");
			return (Criteria) this;
		}

		public Criteria andStaffIdEqualTo(Integer value) {
			addCriterion("staff_id =", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotEqualTo(Integer value) {
			addCriterion("staff_id <>", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThan(Integer value) {
			addCriterion("staff_id >", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("staff_id >=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThan(Integer value) {
			addCriterion("staff_id <", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
			addCriterion("staff_id <=", value, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdIn(List<Integer> values) {
			addCriterion("staff_id in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotIn(List<Integer> values) {
			addCriterion("staff_id not in", values, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdBetween(Integer value1, Integer value2) {
			addCriterion("staff_id between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
			addCriterion("staff_id not between", value1, value2, "staffId");
			return (Criteria) this;
		}

		public Criteria andStaffCodeIsNull() {
			addCriterion("staff_code is null");
			return (Criteria) this;
		}

		public Criteria andStaffCodeIsNotNull() {
			addCriterion("staff_code is not null");
			return (Criteria) this;
		}

		public Criteria andStaffCodeEqualTo(String value) {
			addCriterion("staff_code =", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotEqualTo(String value) {
			addCriterion("staff_code <>", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeGreaterThan(String value) {
			addCriterion("staff_code >", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeGreaterThanOrEqualTo(String value) {
			addCriterion("staff_code >=", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeLessThan(String value) {
			addCriterion("staff_code <", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeLessThanOrEqualTo(String value) {
			addCriterion("staff_code <=", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeLike(String value) {
			addCriterion("staff_code like", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotLike(String value) {
			addCriterion("staff_code not like", value, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeIn(List<String> values) {
			addCriterion("staff_code in", values, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotIn(List<String> values) {
			addCriterion("staff_code not in", values, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeBetween(String value1, String value2) {
			addCriterion("staff_code between", value1, value2, "staffCode");
			return (Criteria) this;
		}

		public Criteria andStaffCodeNotBetween(String value1, String value2) {
			addCriterion("staff_code not between", value1, value2, "staffCode");
			return (Criteria) this;
		}

		public Criteria andPHnIsNull() {
			addCriterion("p_hn is null");
			return (Criteria) this;
		}

		public Criteria andPHnIsNotNull() {
			addCriterion("p_hn is not null");
			return (Criteria) this;
		}

		public Criteria andPHnEqualTo(String value) {
			addCriterion("p_hn =", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnNotEqualTo(String value) {
			addCriterion("p_hn <>", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnGreaterThan(String value) {
			addCriterion("p_hn >", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnGreaterThanOrEqualTo(String value) {
			addCriterion("p_hn >=", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnLessThan(String value) {
			addCriterion("p_hn <", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnLessThanOrEqualTo(String value) {
			addCriterion("p_hn <=", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnLike(String value) {
			addCriterion("p_hn like", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnNotLike(String value) {
			addCriterion("p_hn not like", value, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnIn(List<String> values) {
			addCriterion("p_hn in", values, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnNotIn(List<String> values) {
			addCriterion("p_hn not in", values, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnBetween(String value1, String value2) {
			addCriterion("p_hn between", value1, value2, "pHn");
			return (Criteria) this;
		}

		public Criteria andPHnNotBetween(String value1, String value2) {
			addCriterion("p_hn not between", value1, value2, "pHn");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andErrorCodeIsNull() {
			addCriterion("error_code is null");
			return (Criteria) this;
		}

		public Criteria andErrorCodeIsNotNull() {
			addCriterion("error_code is not null");
			return (Criteria) this;
		}

		public Criteria andErrorCodeEqualTo(Integer value) {
			addCriterion("error_code =", value, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeNotEqualTo(Integer value) {
			addCriterion("error_code <>", value, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeGreaterThan(Integer value) {
			addCriterion("error_code >", value, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("error_code >=", value, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeLessThan(Integer value) {
			addCriterion("error_code <", value, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeLessThanOrEqualTo(Integer value) {
			addCriterion("error_code <=", value, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeIn(List<Integer> values) {
			addCriterion("error_code in", values, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeNotIn(List<Integer> values) {
			addCriterion("error_code not in", values, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeBetween(Integer value1, Integer value2) {
			addCriterion("error_code between", value1, value2, "errorCode");
			return (Criteria) this;
		}

		public Criteria andErrorCodeNotBetween(Integer value1, Integer value2) {
			addCriterion("error_code not between", value1, value2, "errorCode");
			return (Criteria) this;
		}

		public Criteria andIsAckIsNull() {
			addCriterion("is_ack is null");
			return (Criteria) this;
		}

		public Criteria andIsAckIsNotNull() {
			addCriterion("is_ack is not null");
			return (Criteria) this;
		}

		public Criteria andIsAckEqualTo(Integer value) {
			addCriterion("is_ack =", value, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckNotEqualTo(Integer value) {
			addCriterion("is_ack <>", value, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckGreaterThan(Integer value) {
			addCriterion("is_ack >", value, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_ack >=", value, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckLessThan(Integer value) {
			addCriterion("is_ack <", value, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckLessThanOrEqualTo(Integer value) {
			addCriterion("is_ack <=", value, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckIn(List<Integer> values) {
			addCriterion("is_ack in", values, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckNotIn(List<Integer> values) {
			addCriterion("is_ack not in", values, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckBetween(Integer value1, Integer value2) {
			addCriterion("is_ack between", value1, value2, "isAck");
			return (Criteria) this;
		}

		public Criteria andIsAckNotBetween(Integer value1, Integer value2) {
			addCriterion("is_ack not between", value1, value2, "isAck");
			return (Criteria) this;
		}

		public Criteria andExecTimeIsNull() {
			addCriterion("exec_time is null");
			return (Criteria) this;
		}

		public Criteria andExecTimeIsNotNull() {
			addCriterion("exec_time is not null");
			return (Criteria) this;
		}

		public Criteria andExecTimeEqualTo(Date value) {
			addCriterion("exec_time =", value, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeNotEqualTo(Date value) {
			addCriterion("exec_time <>", value, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeGreaterThan(Date value) {
			addCriterion("exec_time >", value, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("exec_time >=", value, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeLessThan(Date value) {
			addCriterion("exec_time <", value, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeLessThanOrEqualTo(Date value) {
			addCriterion("exec_time <=", value, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeIn(List<Date> values) {
			addCriterion("exec_time in", values, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeNotIn(List<Date> values) {
			addCriterion("exec_time not in", values, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeBetween(Date value1, Date value2) {
			addCriterion("exec_time between", value1, value2, "execTime");
			return (Criteria) this;
		}

		public Criteria andExecTimeNotBetween(Date value1, Date value2) {
			addCriterion("exec_time not between", value1, value2, "execTime");
			return (Criteria) this;
		}

		public Criteria andRetryCountIsNull() {
			addCriterion("retry_count is null");
			return (Criteria) this;
		}

		public Criteria andRetryCountIsNotNull() {
			addCriterion("retry_count is not null");
			return (Criteria) this;
		}

		public Criteria andRetryCountEqualTo(Integer value) {
			addCriterion("retry_count =", value, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountNotEqualTo(Integer value) {
			addCriterion("retry_count <>", value, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountGreaterThan(Integer value) {
			addCriterion("retry_count >", value, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("retry_count >=", value, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountLessThan(Integer value) {
			addCriterion("retry_count <", value, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountLessThanOrEqualTo(Integer value) {
			addCriterion("retry_count <=", value, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountIn(List<Integer> values) {
			addCriterion("retry_count in", values, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountNotIn(List<Integer> values) {
			addCriterion("retry_count not in", values, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountBetween(Integer value1, Integer value2) {
			addCriterion("retry_count between", value1, value2, "retryCount");
			return (Criteria) this;
		}

		public Criteria andRetryCountNotBetween(Integer value1, Integer value2) {
			addCriterion("retry_count not between", value1, value2,
					"retryCount");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeIsNull() {
			addCriterion("specimen_type is null");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeIsNotNull() {
			addCriterion("specimen_type is not null");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeEqualTo(String value) {
			addCriterion("specimen_type =", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeNotEqualTo(String value) {
			addCriterion("specimen_type <>", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeGreaterThan(String value) {
			addCriterion("specimen_type >", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeGreaterThanOrEqualTo(String value) {
			addCriterion("specimen_type >=", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeLessThan(String value) {
			addCriterion("specimen_type <", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeLessThanOrEqualTo(String value) {
			addCriterion("specimen_type <=", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeLike(String value) {
			addCriterion("specimen_type like", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeNotLike(String value) {
			addCriterion("specimen_type not like", value, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeIn(List<String> values) {
			addCriterion("specimen_type in", values, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeNotIn(List<String> values) {
			addCriterion("specimen_type not in", values, "specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeBetween(String value1, String value2) {
			addCriterion("specimen_type between", value1, value2,
					"specimenType");
			return (Criteria) this;
		}

		public Criteria andSpecimenTypeNotBetween(String value1, String value2) {
			addCriterion("specimen_type not between", value1, value2,
					"specimenType");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("comment is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("comment is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("comment =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("comment <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("comment >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("comment >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("comment <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("comment <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("comment like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("comment not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("comment in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("comment not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("comment between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("comment not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andIsEditedIsNull() {
			addCriterion("is_edited is null");
			return (Criteria) this;
		}

		public Criteria andIsEditedIsNotNull() {
			addCriterion("is_edited is not null");
			return (Criteria) this;
		}

		public Criteria andIsEditedEqualTo(Integer value) {
			addCriterion("is_edited =", value, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedNotEqualTo(Integer value) {
			addCriterion("is_edited <>", value, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedGreaterThan(Integer value) {
			addCriterion("is_edited >", value, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_edited >=", value, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedLessThan(Integer value) {
			addCriterion("is_edited <", value, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedLessThanOrEqualTo(Integer value) {
			addCriterion("is_edited <=", value, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedIn(List<Integer> values) {
			addCriterion("is_edited in", values, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedNotIn(List<Integer> values) {
			addCriterion("is_edited not in", values, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedBetween(Integer value1, Integer value2) {
			addCriterion("is_edited between", value1, value2, "isEdited");
			return (Criteria) this;
		}

		public Criteria andIsEditedNotBetween(Integer value1, Integer value2) {
			addCriterion("is_edited not between", value1, value2, "isEdited");
			return (Criteria) this;
		}

		public Criteria andPLocIdIsNull() {
			addCriterion("p_loc_id is null");
			return (Criteria) this;
		}

		public Criteria andPLocIdIsNotNull() {
			addCriterion("p_loc_id is not null");
			return (Criteria) this;
		}

		public Criteria andPLocIdEqualTo(Integer value) {
			addCriterion("p_loc_id =", value, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdNotEqualTo(Integer value) {
			addCriterion("p_loc_id <>", value, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdGreaterThan(Integer value) {
			addCriterion("p_loc_id >", value, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("p_loc_id >=", value, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdLessThan(Integer value) {
			addCriterion("p_loc_id <", value, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdLessThanOrEqualTo(Integer value) {
			addCriterion("p_loc_id <=", value, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdIn(List<Integer> values) {
			addCriterion("p_loc_id in", values, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdNotIn(List<Integer> values) {
			addCriterion("p_loc_id not in", values, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdBetween(Integer value1, Integer value2) {
			addCriterion("p_loc_id between", value1, value2, "pLocId");
			return (Criteria) this;
		}

		public Criteria andPLocIdNotBetween(Integer value1, Integer value2) {
			addCriterion("p_loc_id not between", value1, value2, "pLocId");
			return (Criteria) this;
		}

		public Criteria andLabidIsNull() {
			addCriterion("labid is null");
			return (Criteria) this;
		}

		public Criteria andLabidIsNotNull() {
			addCriterion("labid is not null");
			return (Criteria) this;
		}

		public Criteria andLabidEqualTo(String value) {
			addCriterion("labid =", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidNotEqualTo(String value) {
			addCriterion("labid <>", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidGreaterThan(String value) {
			addCriterion("labid >", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidGreaterThanOrEqualTo(String value) {
			addCriterion("labid >=", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidLessThan(String value) {
			addCriterion("labid <", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidLessThanOrEqualTo(String value) {
			addCriterion("labid <=", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidLike(String value) {
			addCriterion("labid like", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidNotLike(String value) {
			addCriterion("labid not like", value, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidIn(List<String> values) {
			addCriterion("labid in", values, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidNotIn(List<String> values) {
			addCriterion("labid not in", values, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidBetween(String value1, String value2) {
			addCriterion("labid between", value1, value2, "labid");
			return (Criteria) this;
		}

		public Criteria andLabidNotBetween(String value1, String value2) {
			addCriterion("labid not between", value1, value2, "labid");
			return (Criteria) this;
		}

		public Criteria andBillIdIsNull() {
			addCriterion("bill_id is null");
			return (Criteria) this;
		}

		public Criteria andBillIdIsNotNull() {
			addCriterion("bill_id is not null");
			return (Criteria) this;
		}

		public Criteria andBillIdEqualTo(String value) {
			addCriterion("bill_id =", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdNotEqualTo(String value) {
			addCriterion("bill_id <>", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdGreaterThan(String value) {
			addCriterion("bill_id >", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdGreaterThanOrEqualTo(String value) {
			addCriterion("bill_id >=", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdLessThan(String value) {
			addCriterion("bill_id <", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdLessThanOrEqualTo(String value) {
			addCriterion("bill_id <=", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdLike(String value) {
			addCriterion("bill_id like", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdNotLike(String value) {
			addCriterion("bill_id not like", value, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdIn(List<String> values) {
			addCriterion("bill_id in", values, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdNotIn(List<String> values) {
			addCriterion("bill_id not in", values, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdBetween(String value1, String value2) {
			addCriterion("bill_id between", value1, value2, "billId");
			return (Criteria) this;
		}

		public Criteria andBillIdNotBetween(String value1, String value2) {
			addCriterion("bill_id not between", value1, value2, "billId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("order_id like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("order_id not like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andEncTypeIsNull() {
			addCriterion("enc_type is null");
			return (Criteria) this;
		}

		public Criteria andEncTypeIsNotNull() {
			addCriterion("enc_type is not null");
			return (Criteria) this;
		}

		public Criteria andEncTypeEqualTo(String value) {
			addCriterion("enc_type =", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeNotEqualTo(String value) {
			addCriterion("enc_type <>", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeGreaterThan(String value) {
			addCriterion("enc_type >", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeGreaterThanOrEqualTo(String value) {
			addCriterion("enc_type >=", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeLessThan(String value) {
			addCriterion("enc_type <", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeLessThanOrEqualTo(String value) {
			addCriterion("enc_type <=", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeLike(String value) {
			addCriterion("enc_type like", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeNotLike(String value) {
			addCriterion("enc_type not like", value, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeIn(List<String> values) {
			addCriterion("enc_type in", values, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeNotIn(List<String> values) {
			addCriterion("enc_type not in", values, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeBetween(String value1, String value2) {
			addCriterion("enc_type between", value1, value2, "encType");
			return (Criteria) this;
		}

		public Criteria andEncTypeNotBetween(String value1, String value2) {
			addCriterion("enc_type not between", value1, value2, "encType");
			return (Criteria) this;
		}

		public Criteria andEncIdIsNull() {
			addCriterion("enc_id is null");
			return (Criteria) this;
		}

		public Criteria andEncIdIsNotNull() {
			addCriterion("enc_id is not null");
			return (Criteria) this;
		}

		public Criteria andEncIdEqualTo(String value) {
			addCriterion("enc_id =", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdNotEqualTo(String value) {
			addCriterion("enc_id <>", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdGreaterThan(String value) {
			addCriterion("enc_id >", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdGreaterThanOrEqualTo(String value) {
			addCriterion("enc_id >=", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdLessThan(String value) {
			addCriterion("enc_id <", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdLessThanOrEqualTo(String value) {
			addCriterion("enc_id <=", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdLike(String value) {
			addCriterion("enc_id like", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdNotLike(String value) {
			addCriterion("enc_id not like", value, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdIn(List<String> values) {
			addCriterion("enc_id in", values, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdNotIn(List<String> values) {
			addCriterion("enc_id not in", values, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdBetween(String value1, String value2) {
			addCriterion("enc_id between", value1, value2, "encId");
			return (Criteria) this;
		}

		public Criteria andEncIdNotBetween(String value1, String value2) {
			addCriterion("enc_id not between", value1, value2, "encId");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIsNull() {
			addCriterion("update_dt is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIsNotNull() {
			addCriterion("update_dt is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDtEqualTo(Date value) {
			addCriterion("update_dt =", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotEqualTo(Date value) {
			addCriterion("update_dt <>", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtGreaterThan(Date value) {
			addCriterion("update_dt >", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtGreaterThanOrEqualTo(Date value) {
			addCriterion("update_dt >=", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtLessThan(Date value) {
			addCriterion("update_dt <", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtLessThanOrEqualTo(Date value) {
			addCriterion("update_dt <=", value, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtIn(List<Date> values) {
			addCriterion("update_dt in", values, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotIn(List<Date> values) {
			addCriterion("update_dt not in", values, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtBetween(Date value1, Date value2) {
			addCriterion("update_dt between", value1, value2, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateDtNotBetween(Date value1, Date value2) {
			addCriterion("update_dt not between", value1, value2, "updateDt");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNull() {
			addCriterion("update_by is null");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNotNull() {
			addCriterion("update_by is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateByEqualTo(Integer value) {
			addCriterion("update_by =", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotEqualTo(Integer value) {
			addCriterion("update_by <>", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThan(Integer value) {
			addCriterion("update_by >", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_by >=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThan(Integer value) {
			addCriterion("update_by <", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThanOrEqualTo(Integer value) {
			addCriterion("update_by <=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByIn(List<Integer> values) {
			addCriterion("update_by in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotIn(List<Integer> values) {
			addCriterion("update_by not in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByBetween(Integer value1, Integer value2) {
			addCriterion("update_by between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotBetween(Integer value1, Integer value2) {
			addCriterion("update_by not between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andRecByCommandIsNull() {
			addCriterion("rec_by_command is null");
			return (Criteria) this;
		}

		public Criteria andRecByCommandIsNotNull() {
			addCriterion("rec_by_command is not null");
			return (Criteria) this;
		}

		public Criteria andRecByCommandEqualTo(String value) {
			addCriterion("rec_by_command =", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandNotEqualTo(String value) {
			addCriterion("rec_by_command <>", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandGreaterThan(String value) {
			addCriterion("rec_by_command >", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandGreaterThanOrEqualTo(String value) {
			addCriterion("rec_by_command >=", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandLessThan(String value) {
			addCriterion("rec_by_command <", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandLessThanOrEqualTo(String value) {
			addCriterion("rec_by_command <=", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandLike(String value) {
			addCriterion("rec_by_command like", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandNotLike(String value) {
			addCriterion("rec_by_command not like", value, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandIn(List<String> values) {
			addCriterion("rec_by_command in", values, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandNotIn(List<String> values) {
			addCriterion("rec_by_command not in", values, "recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandBetween(String value1, String value2) {
			addCriterion("rec_by_command between", value1, value2,
					"recByCommand");
			return (Criteria) this;
		}

		public Criteria andRecByCommandNotBetween(String value1, String value2) {
			addCriterion("rec_by_command not between", value1, value2,
					"recByCommand");
			return (Criteria) this;
		}

		public Criteria andIsprmIsNull() {
			addCriterion("isprm is null");
			return (Criteria) this;
		}

		public Criteria andIsprmIsNotNull() {
			addCriterion("isprm is not null");
			return (Criteria) this;
		}

		public Criteria andIsprmEqualTo(String value) {
			addCriterion("isprm =", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmNotEqualTo(String value) {
			addCriterion("isprm <>", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmGreaterThan(String value) {
			addCriterion("isprm >", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmGreaterThanOrEqualTo(String value) {
			addCriterion("isprm >=", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmLessThan(String value) {
			addCriterion("isprm <", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmLessThanOrEqualTo(String value) {
			addCriterion("isprm <=", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmLike(String value) {
			addCriterion("isprm like", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmNotLike(String value) {
			addCriterion("isprm not like", value, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmIn(List<String> values) {
			addCriterion("isprm in", values, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmNotIn(List<String> values) {
			addCriterion("isprm not in", values, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmBetween(String value1, String value2) {
			addCriterion("isprm between", value1, value2, "isprm");
			return (Criteria) this;
		}

		public Criteria andIsprmNotBetween(String value1, String value2) {
			addCriterion("isprm not between", value1, value2, "isprm");
			return (Criteria) this;
		}

		public Criteria andIfcommentIsNull() {
			addCriterion("ifcomment is null");
			return (Criteria) this;
		}

		public Criteria andIfcommentIsNotNull() {
			addCriterion("ifcomment is not null");
			return (Criteria) this;
		}

		public Criteria andIfcommentEqualTo(String value) {
			addCriterion("ifcomment =", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentNotEqualTo(String value) {
			addCriterion("ifcomment <>", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentGreaterThan(String value) {
			addCriterion("ifcomment >", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentGreaterThanOrEqualTo(String value) {
			addCriterion("ifcomment >=", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentLessThan(String value) {
			addCriterion("ifcomment <", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentLessThanOrEqualTo(String value) {
			addCriterion("ifcomment <=", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentLike(String value) {
			addCriterion("ifcomment like", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentNotLike(String value) {
			addCriterion("ifcomment not like", value, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentIn(List<String> values) {
			addCriterion("ifcomment in", values, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentNotIn(List<String> values) {
			addCriterion("ifcomment not in", values, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentBetween(String value1, String value2) {
			addCriterion("ifcomment between", value1, value2, "ifcomment");
			return (Criteria) this;
		}

		public Criteria andIfcommentNotBetween(String value1, String value2) {
			addCriterion("ifcomment not between", value1, value2, "ifcomment");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table test
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test
     *
     * @mbggenerated do_not_delete_during_merge Tue May 19 01:36:33 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}