package com.healthcare.db.model;

import java.util.Date;

public class TestChangeRevisionsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.test_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Integer testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_change_revisions.change_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	private Date changeDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.test_id
	 * @return  the value of test_change_revisions.test_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Integer getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.test_id
	 * @param testId  the value for test_change_revisions.test_id
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_change_revisions.change_dt
	 * @return  the value of test_change_revisions.change_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public Date getChangeDt() {
		return changeDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_change_revisions.change_dt
	 * @param changeDt  the value for test_change_revisions.change_dt
	 * @mbggenerated  Tue Dec 15 00:20:16 ICT 2015
	 */
	public void setChangeDt(Date changeDt) {
		this.changeDt = changeDt;
	}
}