package com.healthcare.db.model;

import java.util.ArrayList;
import java.util.List;

public class AnalyzerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public AnalyzerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAnalyzerIdIsNull() {
			addCriterion("analyzer_id is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIsNotNull() {
			addCriterion("analyzer_id is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdEqualTo(Integer value) {
			addCriterion("analyzer_id =", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotEqualTo(Integer value) {
			addCriterion("analyzer_id <>", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThan(Integer value) {
			addCriterion("analyzer_id >", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id >=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThan(Integer value) {
			addCriterion("analyzer_id <", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdLessThanOrEqualTo(Integer value) {
			addCriterion("analyzer_id <=", value, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdIn(List<Integer> values) {
			addCriterion("analyzer_id in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotIn(List<Integer> values) {
			addCriterion("analyzer_id not in", values, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id between", value1, value2, "analyzerId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_id not between", value1, value2,
					"analyzerId");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNull() {
			addCriterion("tr_id is null");
			return (Criteria) this;
		}

		public Criteria andTrIdIsNotNull() {
			addCriterion("tr_id is not null");
			return (Criteria) this;
		}

		public Criteria andTrIdEqualTo(Integer value) {
			addCriterion("tr_id =", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotEqualTo(Integer value) {
			addCriterion("tr_id <>", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThan(Integer value) {
			addCriterion("tr_id >", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("tr_id >=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThan(Integer value) {
			addCriterion("tr_id <", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdLessThanOrEqualTo(Integer value) {
			addCriterion("tr_id <=", value, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdIn(List<Integer> values) {
			addCriterion("tr_id in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotIn(List<Integer> values) {
			addCriterion("tr_id not in", values, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdBetween(Integer value1, Integer value2) {
			addCriterion("tr_id between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andTrIdNotBetween(Integer value1, Integer value2) {
			addCriterion("tr_id not between", value1, value2, "trId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialIsNull() {
			addCriterion("analyzer_serial is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialIsNotNull() {
			addCriterion("analyzer_serial is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialEqualTo(String value) {
			addCriterion("analyzer_serial =", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialNotEqualTo(String value) {
			addCriterion("analyzer_serial <>", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialGreaterThan(String value) {
			addCriterion("analyzer_serial >", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialGreaterThanOrEqualTo(String value) {
			addCriterion("analyzer_serial >=", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialLessThan(String value) {
			addCriterion("analyzer_serial <", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialLessThanOrEqualTo(String value) {
			addCriterion("analyzer_serial <=", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialLike(String value) {
			addCriterion("analyzer_serial like", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialNotLike(String value) {
			addCriterion("analyzer_serial not like", value, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialIn(List<String> values) {
			addCriterion("analyzer_serial in", values, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialNotIn(List<String> values) {
			addCriterion("analyzer_serial not in", values, "analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialBetween(String value1, String value2) {
			addCriterion("analyzer_serial between", value1, value2,
					"analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerSerialNotBetween(String value1, String value2) {
			addCriterion("analyzer_serial not between", value1, value2,
					"analyzerSerial");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelIsNull() {
			addCriterion("analyzer_model is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelIsNotNull() {
			addCriterion("analyzer_model is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelEqualTo(String value) {
			addCriterion("analyzer_model =", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelNotEqualTo(String value) {
			addCriterion("analyzer_model <>", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelGreaterThan(String value) {
			addCriterion("analyzer_model >", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelGreaterThanOrEqualTo(String value) {
			addCriterion("analyzer_model >=", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelLessThan(String value) {
			addCriterion("analyzer_model <", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelLessThanOrEqualTo(String value) {
			addCriterion("analyzer_model <=", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelLike(String value) {
			addCriterion("analyzer_model like", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelNotLike(String value) {
			addCriterion("analyzer_model not like", value, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelIn(List<String> values) {
			addCriterion("analyzer_model in", values, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelNotIn(List<String> values) {
			addCriterion("analyzer_model not in", values, "analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelBetween(String value1, String value2) {
			addCriterion("analyzer_model between", value1, value2,
					"analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerModelNotBetween(String value1, String value2) {
			addCriterion("analyzer_model not between", value1, value2,
					"analyzerModel");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameIsNull() {
			addCriterion("analyzer_name is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameIsNotNull() {
			addCriterion("analyzer_name is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameEqualTo(String value) {
			addCriterion("analyzer_name =", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameNotEqualTo(String value) {
			addCriterion("analyzer_name <>", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameGreaterThan(String value) {
			addCriterion("analyzer_name >", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameGreaterThanOrEqualTo(String value) {
			addCriterion("analyzer_name >=", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameLessThan(String value) {
			addCriterion("analyzer_name <", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameLessThanOrEqualTo(String value) {
			addCriterion("analyzer_name <=", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameLike(String value) {
			addCriterion("analyzer_name like", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameNotLike(String value) {
			addCriterion("analyzer_name not like", value, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameIn(List<String> values) {
			addCriterion("analyzer_name in", values, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameNotIn(List<String> values) {
			addCriterion("analyzer_name not in", values, "analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameBetween(String value1, String value2) {
			addCriterion("analyzer_name between", value1, value2,
					"analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerNameNotBetween(String value1, String value2) {
			addCriterion("analyzer_name not between", value1, value2,
					"analyzerName");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdIsNull() {
			addCriterion("analyzer_group_id is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdIsNotNull() {
			addCriterion("analyzer_group_id is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdEqualTo(Integer value) {
			addCriterion("analyzer_group_id =", value, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdNotEqualTo(Integer value) {
			addCriterion("analyzer_group_id <>", value, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdGreaterThan(Integer value) {
			addCriterion("analyzer_group_id >", value, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("analyzer_group_id >=", value, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdLessThan(Integer value) {
			addCriterion("analyzer_group_id <", value, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdLessThanOrEqualTo(Integer value) {
			addCriterion("analyzer_group_id <=", value, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdIn(List<Integer> values) {
			addCriterion("analyzer_group_id in", values, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdNotIn(List<Integer> values) {
			addCriterion("analyzer_group_id not in", values, "analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdBetween(Integer value1, Integer value2) {
			addCriterion("analyzer_group_id between", value1, value2,
					"analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerGroupIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("analyzer_group_id not between", value1, value2,
					"analyzerGroupId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInIsNull() {
			addCriterion("analyzer_in is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInIsNotNull() {
			addCriterion("analyzer_in is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInEqualTo(String value) {
			addCriterion("analyzer_in =", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInNotEqualTo(String value) {
			addCriterion("analyzer_in <>", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInGreaterThan(String value) {
			addCriterion("analyzer_in >", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInGreaterThanOrEqualTo(String value) {
			addCriterion("analyzer_in >=", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInLessThan(String value) {
			addCriterion("analyzer_in <", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInLessThanOrEqualTo(String value) {
			addCriterion("analyzer_in <=", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInLike(String value) {
			addCriterion("analyzer_in like", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInNotLike(String value) {
			addCriterion("analyzer_in not like", value, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInIn(List<String> values) {
			addCriterion("analyzer_in in", values, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInNotIn(List<String> values) {
			addCriterion("analyzer_in not in", values, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInBetween(String value1, String value2) {
			addCriterion("analyzer_in between", value1, value2, "analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerInNotBetween(String value1, String value2) {
			addCriterion("analyzer_in not between", value1, value2,
					"analyzerIn");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutIsNull() {
			addCriterion("analyzer_out is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutIsNotNull() {
			addCriterion("analyzer_out is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutEqualTo(String value) {
			addCriterion("analyzer_out =", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutNotEqualTo(String value) {
			addCriterion("analyzer_out <>", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutGreaterThan(String value) {
			addCriterion("analyzer_out >", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutGreaterThanOrEqualTo(String value) {
			addCriterion("analyzer_out >=", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutLessThan(String value) {
			addCriterion("analyzer_out <", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutLessThanOrEqualTo(String value) {
			addCriterion("analyzer_out <=", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutLike(String value) {
			addCriterion("analyzer_out like", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutNotLike(String value) {
			addCriterion("analyzer_out not like", value, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutIn(List<String> values) {
			addCriterion("analyzer_out in", values, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutNotIn(List<String> values) {
			addCriterion("analyzer_out not in", values, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutBetween(String value1, String value2) {
			addCriterion("analyzer_out between", value1, value2, "analyzerOut");
			return (Criteria) this;
		}

		public Criteria andAnalyzerOutNotBetween(String value1, String value2) {
			addCriterion("analyzer_out not between", value1, value2,
					"analyzerOut");
			return (Criteria) this;
		}

		public Criteria andTgIdIsNull() {
			addCriterion("tg_id is null");
			return (Criteria) this;
		}

		public Criteria andTgIdIsNotNull() {
			addCriterion("tg_id is not null");
			return (Criteria) this;
		}

		public Criteria andTgIdEqualTo(Integer value) {
			addCriterion("tg_id =", value, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdNotEqualTo(Integer value) {
			addCriterion("tg_id <>", value, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdGreaterThan(Integer value) {
			addCriterion("tg_id >", value, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("tg_id >=", value, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdLessThan(Integer value) {
			addCriterion("tg_id <", value, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdLessThanOrEqualTo(Integer value) {
			addCriterion("tg_id <=", value, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdIn(List<Integer> values) {
			addCriterion("tg_id in", values, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdNotIn(List<Integer> values) {
			addCriterion("tg_id not in", values, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdBetween(Integer value1, Integer value2) {
			addCriterion("tg_id between", value1, value2, "tgId");
			return (Criteria) this;
		}

		public Criteria andTgIdNotBetween(Integer value1, Integer value2) {
			addCriterion("tg_id not between", value1, value2, "tgId");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescIsNull() {
			addCriterion("analyzer_desc is null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescIsNotNull() {
			addCriterion("analyzer_desc is not null");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescEqualTo(String value) {
			addCriterion("analyzer_desc =", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescNotEqualTo(String value) {
			addCriterion("analyzer_desc <>", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescGreaterThan(String value) {
			addCriterion("analyzer_desc >", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescGreaterThanOrEqualTo(String value) {
			addCriterion("analyzer_desc >=", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescLessThan(String value) {
			addCriterion("analyzer_desc <", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescLessThanOrEqualTo(String value) {
			addCriterion("analyzer_desc <=", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescLike(String value) {
			addCriterion("analyzer_desc like", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescNotLike(String value) {
			addCriterion("analyzer_desc not like", value, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescIn(List<String> values) {
			addCriterion("analyzer_desc in", values, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescNotIn(List<String> values) {
			addCriterion("analyzer_desc not in", values, "analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescBetween(String value1, String value2) {
			addCriterion("analyzer_desc between", value1, value2,
					"analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andAnalyzerDescNotBetween(String value1, String value2) {
			addCriterion("analyzer_desc not between", value1, value2,
					"analyzerDesc");
			return (Criteria) this;
		}

		public Criteria andWardIdIsNull() {
			addCriterion("ward_id is null");
			return (Criteria) this;
		}

		public Criteria andWardIdIsNotNull() {
			addCriterion("ward_id is not null");
			return (Criteria) this;
		}

		public Criteria andWardIdEqualTo(Integer value) {
			addCriterion("ward_id =", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotEqualTo(Integer value) {
			addCriterion("ward_id <>", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdGreaterThan(Integer value) {
			addCriterion("ward_id >", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ward_id >=", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdLessThan(Integer value) {
			addCriterion("ward_id <", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdLessThanOrEqualTo(Integer value) {
			addCriterion("ward_id <=", value, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdIn(List<Integer> values) {
			addCriterion("ward_id in", values, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotIn(List<Integer> values) {
			addCriterion("ward_id not in", values, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdBetween(Integer value1, Integer value2) {
			addCriterion("ward_id between", value1, value2, "wardId");
			return (Criteria) this;
		}

		public Criteria andWardIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ward_id not between", value1, value2, "wardId");
			return (Criteria) this;
		}

		public Criteria andServiceCodeIsNull() {
			addCriterion("service_code is null");
			return (Criteria) this;
		}

		public Criteria andServiceCodeIsNotNull() {
			addCriterion("service_code is not null");
			return (Criteria) this;
		}

		public Criteria andServiceCodeEqualTo(String value) {
			addCriterion("service_code =", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeNotEqualTo(String value) {
			addCriterion("service_code <>", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeGreaterThan(String value) {
			addCriterion("service_code >", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeGreaterThanOrEqualTo(String value) {
			addCriterion("service_code >=", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeLessThan(String value) {
			addCriterion("service_code <", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeLessThanOrEqualTo(String value) {
			addCriterion("service_code <=", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeLike(String value) {
			addCriterion("service_code like", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeNotLike(String value) {
			addCriterion("service_code not like", value, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeIn(List<String> values) {
			addCriterion("service_code in", values, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeNotIn(List<String> values) {
			addCriterion("service_code not in", values, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeBetween(String value1, String value2) {
			addCriterion("service_code between", value1, value2, "serviceCode");
			return (Criteria) this;
		}

		public Criteria andServiceCodeNotBetween(String value1, String value2) {
			addCriterion("service_code not between", value1, value2,
					"serviceCode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table analyzer
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table analyzer
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 01 16:59:43 ICT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}