package com.healthcare.db.model;

import java.util.Date;

public class Calibration {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.calibration_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private Integer calibrationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.tr_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private Integer trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.calibration_dt
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private Date calibrationDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.calibration_type
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private String calibrationType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.analyzer_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private Integer analyzerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.lot_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private Integer lotId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.ward_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private Integer wardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.calibration_status
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private Integer calibrationStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.staff_code
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private String staffCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calibration.comment
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.calibration_id
	 * @return  the value of calibration.calibration_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public Integer getCalibrationId() {
		return calibrationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.calibration_id
	 * @param calibrationId  the value for calibration.calibration_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setCalibrationId(Integer calibrationId) {
		this.calibrationId = calibrationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.tr_id
	 * @return  the value of calibration.tr_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public Integer getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.tr_id
	 * @param trId  the value for calibration.tr_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setTrId(Integer trId) {
		this.trId = trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.calibration_dt
	 * @return  the value of calibration.calibration_dt
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public Date getCalibrationDt() {
		return calibrationDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.calibration_dt
	 * @param calibrationDt  the value for calibration.calibration_dt
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setCalibrationDt(Date calibrationDt) {
		this.calibrationDt = calibrationDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.calibration_type
	 * @return  the value of calibration.calibration_type
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public String getCalibrationType() {
		return calibrationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.calibration_type
	 * @param calibrationType  the value for calibration.calibration_type
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setCalibrationType(String calibrationType) {
		this.calibrationType = calibrationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.analyzer_id
	 * @return  the value of calibration.analyzer_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public Integer getAnalyzerId() {
		return analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.analyzer_id
	 * @param analyzerId  the value for calibration.analyzer_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setAnalyzerId(Integer analyzerId) {
		this.analyzerId = analyzerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.lot_id
	 * @return  the value of calibration.lot_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public Integer getLotId() {
		return lotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.lot_id
	 * @param lotId  the value for calibration.lot_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setLotId(Integer lotId) {
		this.lotId = lotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.ward_id
	 * @return  the value of calibration.ward_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public Integer getWardId() {
		return wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.ward_id
	 * @param wardId  the value for calibration.ward_id
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setWardId(Integer wardId) {
		this.wardId = wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.calibration_status
	 * @return  the value of calibration.calibration_status
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public Integer getCalibrationStatus() {
		return calibrationStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.calibration_status
	 * @param calibrationStatus  the value for calibration.calibration_status
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setCalibrationStatus(Integer calibrationStatus) {
		this.calibrationStatus = calibrationStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.staff_code
	 * @return  the value of calibration.staff_code
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public String getStaffCode() {
		return staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.staff_code
	 * @param staffCode  the value for calibration.staff_code
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calibration.comment
	 * @return  the value of calibration.comment
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calibration.comment
	 * @param comment  the value for calibration.comment
	 * @mbggenerated  Mon Jul 27 06:27:29 ICT 2015
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}