package com.healthcare.db.model;

public class Calibrationitem extends CalibrationitemKey {
	
	private String tableName;
    public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calibrationitem.value
     *
     * @mbggenerated Mon Jul 27 06:12:59 ICT 2015
     */
    private Float value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calibrationitem.istatus
     *
     * @mbggenerated Mon Jul 27 06:12:59 ICT 2015
     */
    private Integer istatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calibrationitem.value
     *
     * @return the value of calibrationitem.value
     *
     * @mbggenerated Mon Jul 27 06:12:59 ICT 2015
     */
    public Float getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calibrationitem.value
     *
     * @param value the value for calibrationitem.value
     *
     * @mbggenerated Mon Jul 27 06:12:59 ICT 2015
     */
    public void setValue(Float value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calibrationitem.istatus
     *
     * @return the value of calibrationitem.istatus
     *
     * @mbggenerated Mon Jul 27 06:12:59 ICT 2015
     */
    public Integer getIstatus() {
        return istatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calibrationitem.istatus
     *
     * @param istatus the value for calibrationitem.istatus
     *
     * @mbggenerated Mon Jul 27 06:12:59 ICT 2015
     */
    public void setIstatus(Integer istatus) {
        this.istatus = istatus;
    }
}