package com.healthcare.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class IqmDatasetItem {

	private String tableName;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.result_item_id
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Integer resultItemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.iqm_data_set_id
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Integer iqmDataSetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.test_date
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Date testDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.test_count
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Integer testCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.result_a
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Double resultA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.result_b
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Double resultB;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.result_c
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Double resultC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iqm_dataset_item.result_d
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	private Double resultD;
	
	public String getTableName() {
		return tableName;
	}
	
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.result_item_id
	 * @return  the value of iqm_dataset_item.result_item_id
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Integer getResultItemId() {
		return resultItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.result_item_id
	 * @param resultItemId  the value for iqm_dataset_item.result_item_id
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setResultItemId(Integer resultItemId) {
		this.resultItemId = resultItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.iqm_data_set_id
	 * @return  the value of iqm_dataset_item.iqm_data_set_id
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Integer getIqmDataSetId() {
		return iqmDataSetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.iqm_data_set_id
	 * @param iqmDataSetId  the value for iqm_dataset_item.iqm_data_set_id
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setIqmDataSetId(Integer iqmDataSetId) {
		this.iqmDataSetId = iqmDataSetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.test_date
	 * @return  the value of iqm_dataset_item.test_date
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Date getTestDate() {
		return testDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.test_date
	 * @param testDate  the value for iqm_dataset_item.test_date
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.test_count
	 * @return  the value of iqm_dataset_item.test_count
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Integer getTestCount() {
		return testCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.test_count
	 * @param testCount  the value for iqm_dataset_item.test_count
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setTestCount(Integer testCount) {
		this.testCount = testCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.result_a
	 * @return  the value of iqm_dataset_item.result_a
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Double getResultA() {
		return resultA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.result_a
	 * @param resultA  the value for iqm_dataset_item.result_a
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setResultA(Double resultA) {
		this.resultA = resultA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.result_b
	 * @return  the value of iqm_dataset_item.result_b
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Double getResultB() {
		return resultB;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.result_b
	 * @param resultB  the value for iqm_dataset_item.result_b
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setResultB(Double resultB) {
		this.resultB = resultB;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.result_c
	 * @return  the value of iqm_dataset_item.result_c
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Double getResultC() {
		return resultC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.result_c
	 * @param resultC  the value for iqm_dataset_item.result_c
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setResultC(Double resultC) {
		this.resultC = resultC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iqm_dataset_item.result_d
	 * @return  the value of iqm_dataset_item.result_d
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public Double getResultD() {
		return resultD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iqm_dataset_item.result_d
	 * @param resultD  the value for iqm_dataset_item.result_d
	 * @mbggenerated  Wed Oct 15 12:30:42 ICT 2014
	 */
	public void setResultD(Double resultD) {
		this.resultD = resultD;
	}
}