package com.healthcare.db.model;

public class Newtestitem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtestitem.test_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtestitem.item_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private Integer itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtestitem.value
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtestitem.comment
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column newtestitem.errorcode
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	private String errorcode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtestitem.test_id
	 * @return  the value of newtestitem.test_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtestitem.test_id
	 * @param testId  the value for newtestitem.test_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtestitem.item_id
	 * @return  the value of newtestitem.item_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public Integer getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtestitem.item_id
	 * @param itemId  the value for newtestitem.item_id
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtestitem.value
	 * @return  the value of newtestitem.value
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtestitem.value
	 * @param value  the value for newtestitem.value
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtestitem.comment
	 * @return  the value of newtestitem.comment
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtestitem.comment
	 * @param comment  the value for newtestitem.comment
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column newtestitem.errorcode
	 * @return  the value of newtestitem.errorcode
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public String getErrorcode() {
		return errorcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column newtestitem.errorcode
	 * @param errorcode  the value for newtestitem.errorcode
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	public void setErrorcode(String errorcode) {
		this.errorcode = errorcode;
	}
}