package com.healthcare.db.model;

import java.util.Date;

public class StationStat extends StationStatKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_stat.tracking_status_code
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    private Integer trackingStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_stat.update_time
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_stat.client_source
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    private String clientSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_stat.tracking_status_code
     *
     * @return the value of station_stat.tracking_status_code
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    public Integer getTrackingStatusCode() {
        return trackingStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_stat.tracking_status_code
     *
     * @param trackingStatusCode the value for station_stat.tracking_status_code
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    public void setTrackingStatusCode(Integer trackingStatusCode) {
        this.trackingStatusCode = trackingStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_stat.update_time
     *
     * @return the value of station_stat.update_time
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_stat.update_time
     *
     * @param updateTime the value for station_stat.update_time
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_stat.client_source
     *
     * @return the value of station_stat.client_source
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    public String getClientSource() {
        return clientSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_stat.client_source
     *
     * @param clientSource the value for station_stat.client_source
     *
     * @mbggenerated Sun Dec 21 23:30:03 ICT 2014
     */
    public void setClientSource(String clientSource) {
        this.clientSource = clientSource;
    }
}