package com.healthcare.db.model;

public class Ward {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ward.ward_id
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	private Integer wardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ward.tr_id
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	private Integer trId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ward.ward_name
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	private String wardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ward.ward_in
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	private String wardIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ward.ward_desc
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	private String wardDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ward.ward_group
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	private Integer wardGroup;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ward.ward_id
	 * @return  the value of ward.ward_id
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public Integer getWardId() {
		return wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ward.ward_id
	 * @param wardId  the value for ward.ward_id
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setWardId(Integer wardId) {
		this.wardId = wardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ward.tr_id
	 * @return  the value of ward.tr_id
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public Integer getTrId() {
		return trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ward.tr_id
	 * @param trId  the value for ward.tr_id
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setTrId(Integer trId) {
		this.trId = trId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ward.ward_name
	 * @return  the value of ward.ward_name
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public String getWardName() {
		return wardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ward.ward_name
	 * @param wardName  the value for ward.ward_name
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setWardName(String wardName) {
		this.wardName = wardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ward.ward_in
	 * @return  the value of ward.ward_in
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public String getWardIn() {
		return wardIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ward.ward_in
	 * @param wardIn  the value for ward.ward_in
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setWardIn(String wardIn) {
		this.wardIn = wardIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ward.ward_desc
	 * @return  the value of ward.ward_desc
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public String getWardDesc() {
		return wardDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ward.ward_desc
	 * @param wardDesc  the value for ward.ward_desc
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setWardDesc(String wardDesc) {
		this.wardDesc = wardDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ward.ward_group
	 * @return  the value of ward.ward_group
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public Integer getWardGroup() {
		return wardGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ward.ward_group
	 * @param wardGroup  the value for ward.ward_group
	 * @mbggenerated  Tue Jun 16 02:52:29 ICT 2015
	 */
	public void setWardGroup(Integer wardGroup) {
		this.wardGroup = wardGroup;
	}
}