package com.healthcare.db.client;

import com.healthcare.db.model.Itemdata;
import com.healthcare.db.model.ItemdataExample;
import com.healthcare.db.model.ItemdataWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemdataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int countByExample(ItemdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int deleteByExample(ItemdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int deleteByPrimaryKey(Integer itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int insert(ItemdataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int insertSelective(ItemdataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	List<ItemdataWithBLOBs> selectByExampleWithBLOBs(ItemdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	List<Itemdata> selectByExample(ItemdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	ItemdataWithBLOBs selectByPrimaryKey(Integer itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByExampleSelective(@Param("record") ItemdataWithBLOBs record,
			@Param("example") ItemdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") ItemdataWithBLOBs record,
			@Param("example") ItemdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByExample(@Param("record") Itemdata record,
			@Param("example") ItemdataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByPrimaryKeySelective(ItemdataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByPrimaryKeyWithBLOBs(ItemdataWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemdata
	 * @mbggenerated  Tue Apr 01 20:15:29 ICT 2014
	 */
	int updateByPrimaryKey(Itemdata record);
}