package com.healthcare.db.client;

import com.healthcare.db.model.ItemConversion;
import com.healthcare.db.model.ItemConversionExample;
import com.healthcare.db.model.ItemConversionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemConversionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int countByExample(ItemConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int deleteByExample(ItemConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int deleteByPrimaryKey(ItemConversionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int insert(ItemConversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int insertSelective(ItemConversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    List<ItemConversion> selectByExample(ItemConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    ItemConversion selectByPrimaryKey(ItemConversionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int updateByExampleSelective(@Param("record") ItemConversion record, @Param("example") ItemConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int updateByExample(@Param("record") ItemConversion record, @Param("example") ItemConversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int updateByPrimaryKeySelective(ItemConversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_conversion
     *
     * @mbggenerated Mon Jul 27 08:50:25 ICT 2015
     */
    int updateByPrimaryKey(ItemConversion record);
}