package com.healthcare.db.client;

import com.healthcare.db.model.Lot;
import com.healthcare.db.model.LotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LotMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int countByExample(LotExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int deleteByExample(LotExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int deleteByPrimaryKey(Integer lotId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int insert(Lot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int insertSelective(Lot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	List<Lot> selectByExample(LotExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	Lot selectByPrimaryKey(Integer lotId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int updateByExampleSelective(@Param("record") Lot record,
			@Param("example") LotExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int updateByExample(@Param("record") Lot record,
			@Param("example") LotExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int updateByPrimaryKeySelective(Lot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lot
	 * @mbggenerated  Tue Jun 16 03:39:42 ICT 2015
	 */
	int updateByPrimaryKey(Lot record);
}