package com.healthcare.db.client;

import com.healthcare.db.model.Patient;
import com.healthcare.db.model.PatientExample;
import com.healthcare.db.model.PatientWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int countByExample(PatientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int deleteByExample(PatientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int deleteByPrimaryKey(Integer pId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int insert(Patient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int insertSelective(Patient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	List<Patient> selectByExample(PatientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	Patient selectByPrimaryKey(Integer pId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int updateByExampleSelective(@Param("record") Patient record,
			@Param("example") PatientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int updateByExample(@Param("record") Patient record,
			@Param("example") PatientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int updateByPrimaryKeySelective(Patient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient
	 * @mbggenerated  Tue Nov 18 08:55:43 ICT 2014
	 */
	int updateByPrimaryKey(Patient record);
}