package com.healthcare.db.client;

import com.healthcare.db.model.Staff;
import com.healthcare.db.model.StaffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StaffMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int countByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int deleteByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int deleteByPrimaryKey(Integer staffId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int insert(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int insertSelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	List<Staff> selectByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	Staff selectByPrimaryKey(Integer staffId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int updateByExampleSelective(@Param("record") Staff record,
			@Param("example") StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int updateByExample(@Param("record") Staff record,
			@Param("example") StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int updateByPrimaryKeySelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table staff
	 * @mbggenerated  Tue Dec 02 11:03:18 ICT 2014
	 */
	int updateByPrimaryKey(Staff record);
}