package com.healthcare.db.client;

import com.healthcare.db.model.Systemconfigure;
import com.healthcare.db.model.SystemconfigureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemconfigureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int countByExample(SystemconfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int deleteByExample(SystemconfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int deleteByPrimaryKey(Integer confId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int insert(Systemconfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int insertSelective(Systemconfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    List<Systemconfigure> selectByExample(SystemconfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    Systemconfigure selectByPrimaryKey(Integer confId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int updateByExampleSelective(@Param("record") Systemconfigure record, @Param("example") SystemconfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int updateByExample(@Param("record") Systemconfigure record, @Param("example") SystemconfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int updateByPrimaryKeySelective(Systemconfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemconfigure
     *
     * @mbggenerated Mon Dec 15 23:30:49 ICT 2014
     */
    int updateByPrimaryKey(Systemconfigure record);
}